# Import packages

In [1]:
import os, requests, re, pickle
from pprint import pprint
import pandas as pd
from io import StringIO

# Custom functions

In [2]:
from tools.create_jaspar_filters import obtain_taxonomy_id, obtain_all_cell_lines, \
    cell_lines_df_clear_save


def extract_cell_line_names(input_cell_line_df):
    cell_line_names = [name for name_list in input_cell_line_df['cell_line_name'] for name in
                       name_list.split(',')]  #Pool all the names into a 1D list
    cell_line_names_stripped = [re.sub(r'[^A-Za-z0-9]', '', name) for name in
                                cell_line_names]  #It seems like the stripped cell line names are just the original names with all the special char and spaces removed

    cell_line_names_total = cell_line_names + cell_line_names_stripped
    cell_line_names_total = list(set(cell_line_names_total))  #Remove duplicated names

    cell_line_names_total.sort()
    return cell_line_names_total


def cell_line_names_to_model_id(cell_line_names, model_df):
    model_df_filtered = model_df[
        model_df["CellLineName"].isin(cell_line_names) |
        model_df["StrippedCellLineName"].isin(cell_line_names)
        ]

    model_df_filtered = model_df_filtered.reset_index(drop=True)
    model_id = model_df_filtered['ModelID'].tolist()

    return model_id


def strip_col_gene_name(col_name):
    match = re.match(r"^(.+?)\s*\(\d+\)$", str(col_name))

    if match:
        return match.group(1)
    else:
        return col_name





def expression_df_filterd_by_cell_lines(whole_expression_df, model_id_cell_lines):
    expression_df_cell_lines = whole_expression_df[whole_expression_df['Unnamed: 0'].isin(model_id_cell_lines)]
    expression_df_cell_lines = expression_df_cell_lines.reset_index(drop=True)  # expression_df_cell_lines now contains all the cell lines ModelID and expressed proteins

    expression_df_cell_lines.columns = [strip_col_gene_name(col) for col in expression_df_cell_lines.columns]  # Clean the col title so expression_df_cell_lines's col now only have the gene name
    expression_df_cell_lines = expression_df_cell_lines.rename(columns={'Unnamed: 0': 'ModelID'})  # Rename the first col into 'ModelID'. expression_df_cell_lines now has all the genes expressed by melanoma cell lines

    return expression_df_cell_lines

def expression_df_cell_lines_filtered_by_tf(expression_df_cell_lines, whole_tf_names):
    expression_tf_df_cell_lines = expression_df_cell_lines.loc[:, expression_df_cell_lines.columns.isin(whole_tf_names + ['ModelID'])].copy() #expression_tf_df_cell_lines has all the TF expressed in cell lines

    return expression_tf_df_cell_lines

def expression_tf_df_cell_lines_to_tf_list(expression_tf_df_cell_lines, TPM_LOGP1_threshold, FRACTION_REQUIRED, cell_name):
    expr_only = expression_tf_df_cell_lines.iloc[:, 1:] # Exclude the 1st col which are the ModelID

    frac_expressed = (expr_only >= TPM_LOGP1_threshold).sum(axis=0) / expr_only.shape[0]

    expressed_mask = frac_expressed >= FRACTION_REQUIRED
    expressed_tf = expr_only.columns[expressed_mask].tolist()
    expressed_tf = sorted(expressed_tf)

    print(f'Found {len(expressed_tf)} TF from JASPAR dataset for TF expressed in specific {cell_name.upper()} cell lines')
    # print(expressed_tf)

    with open(f'input/filters/tf_{cell_name}.pkl', 'wb') as file:
        pickle.dump(expressed_tf, file)
    with open(f'input/filters/tf_{cell_name}.txt', 'w') as file:
        if len(expressed_tf) != 0:
            for tf in expressed_tf:
                file.write(tf+'\n')
        else:
            file.write('')

    print(f'Files saved for names of TF expressed in {cell_name.upper()} cell lines')

    del expressed_tf

def expression_df_to_expression_tf_df_cell_lines(whole_expression_df, model_id_cell_lines,whole_tf_names, TPM_LOGP1_threshold, FRACTION_REQUIRED, cell_name):
    expression_df_cell_lines = expression_df_filterd_by_cell_lines(whole_expression_df, model_id_cell_lines)

    expression_tf_df_cell_lines = expression_df_cell_lines_filtered_by_tf(expression_df_cell_lines, whole_tf_names)

    expression_tf_df_cell_lines_to_tf_list(expression_tf_df_cell_lines, TPM_LOGP1_threshold, FRACTION_REQUIRED, cell_name)

    del expression_df_cell_lines, expression_tf_df_cell_lines

# Download datasets

## Cellosaurus
This provides all the cell lines of interests

Cellosaurus API methods & exploration: https://api.cellosaurus.org/api-methods#/

### Obtain taxonomy code
This can be used later to filter cell lines by species

In [3]:
species_search_term = 'Homo sapiens'
tax_id = obtain_taxonomy_id(species_search_term)

Taxonomy ID for Homo sapiens: 9606

### Obtain cell lines

In [4]:
save_dir_cell_lines = 'input/cell_lines'
os.makedirs(save_dir_cell_lines, exist_ok=True)

In [5]:
search_list = [
    {
        'search_term': 'melanoma',
        'search_term_type': 'di'  #Because melanoma is a disease
    },
    {
        'search_term': 'astrocyte',
        'search_term_type': 'cell-type'  #Because astrocyte is a cell type
    }
]

for search_dict in search_list:
    search_term = search_dict['search_term']
    print(f'>>>> Working on {search_term}')
    search_term_type = search_dict['search_term_type']

    all_cell_lines_data = obtain_all_cell_lines(
        search_term,
        search_term_type,
        tax_id,
        1000
    )

    cell_line_df = cell_lines_df_clear_save(all_cell_lines_data, search_term, save_dir_cell_lines)

    print(f'>>>> All {search_term} cell lines dataset has been saved')

>>>> Working on melanoma
Concepts obtained: 0 to 1000
Concepts obtained: 1000 to 2000
Concepts obtained: 2000 to 2995
Total cell line(s) retrieved for melanoma: 2995
CVCL_VU92 lacks derived-from-site-list
CVCL_VU92 lacks derived-from-site-list
CVCL_8471 lacks derived-from-site-list
CVCL_8471 lacks derived-from-site-list
CVCL_C7UC lacks derived-from-site-list
CVCL_C7UC lacks derived-from-site-list
CVCL_C7UD lacks derived-from-site-list
CVCL_C7UD lacks derived-from-site-list
CVCL_C7UF lacks derived-from-site-list
CVCL_C7UF lacks derived-from-site-list
CVCL_C7UG lacks derived-from-site-list
CVCL_C7UG lacks derived-from-site-list
CVCL_M215 lacks derived-from-site-list
CVCL_M215 lacks derived-from-site-list
CVCL_M216 lacks derived-from-site-list
CVCL_M216 lacks derived-from-site-list
CVCL_M217 lacks derived-from-site-list
CVCL_M217 lacks derived-from-site-list
CVCL_M218 lacks derived-from-site-list
CVCL_M218 lacks derived-from-site-list
CVCL_8472 lacks derived-from-site-list
CVCL_8472 lacks derived-from-site-list
CVCL_8473 lacks derived-from-site-list
CVCL_8473 lacks derived-from-site-list
CVCL_8474 lacks derived-from-site-list
CVCL_8474 lacks derived-from-site-list
CVCL_8475 lacks derived-from-site-list
CVCL_8475 lacks derived-from-site-list
CVCL_D714 lacks derived-from-site-list
CVCL_D714 lacks derived-from-site-list
CVCL_D715 lacks derived-from-site-list
CVCL_D715 lacks derived-from-site-list
CVCL_7080 lacks derived-from-site-list
CVCL_7080 lacks derived-from-site-list
CVCL_YL63 lacks derived-from-site-list
CVCL_YL63 lacks derived-from-site-list
CVCL_YL05 lacks derived-from-site-list
CVCL_YL05 lacks derived-from-site-list
CVCL_YL64 lacks derived-from-site-list
CVCL_YL64 lacks derived-from-site-list
CVCL_YL65 lacks derived-from-site-list
CVCL_YL65 lacks derived-from-site-list
CVCL_3447 lacks derived-from-site-list
CVCL_3447 lacks derived-from-site-list
CVCL_6936 lacks derived-from-site-list
CVCL_6936 lacks derived-from-site-list
CVCL_J309 lacks derived-from-site-list
CVCL_J309 lacks derived-from-site-list
CVCL_J310 lacks derived-from-site-list
CVCL_J310 lacks derived-from-site-list
CVCL_J311 lacks derived-from-site-list
CVCL_J311 lacks derived-from-site-list
CVCL_C308 lacks derived-from-site-list
CVCL_C308 lacks derived-from-site-list
CVCL_C8VM lacks derived-from-site-list
CVCL_C8VM lacks derived-from-site-list
CVCL_J307 lacks derived-from-site-list
CVCL_J307 lacks derived-from-site-list
CVCL_VP04 lacks derived-from-site-list
CVCL_VP04 lacks derived-from-site-list
CVCL_VP05 lacks derived-from-site-list
CVCL_VP05 lacks derived-from-site-list
CVCL_VP03 lacks derived-from-site-list
CVCL_VP03 lacks derived-from-site-list
CVCL_VN99 lacks derived-from-site-list
CVCL_VN99 lacks derived-from-site-list
CVCL_J305 lacks derived-from-site-list
CVCL_J305 lacks derived-from-site-list
CVCL_J306 lacks derived-from-site-list
CVCL_J306 lacks derived-from-site-list
CVCL_K005 lacks derived-from-site-list
CVCL_K005 lacks derived-from-site-list
CVCL_K010 lacks derived-from-site-list
CVCL_K010 lacks derived-from-site-list
CVCL_U803 lacks derived-from-site-list
CVCL_U803 lacks derived-from-site-list
CVCL_M777 lacks derived-from-site-list
CVCL_M777 lacks derived-from-site-list
CVCL_U802 lacks derived-from-site-list
CVCL_U802 lacks derived-from-site-list
CVCL_E7UK lacks derived-from-site-list
CVCL_E7UK lacks derived-from-site-list
CVCL_E7UL lacks derived-from-site-list
CVCL_E7UL lacks derived-from-site-list
CVCL_E7UM lacks derived-from-site-list
CVCL_E7UM lacks derived-from-site-list
CVCL_E7UN lacks derived-from-site-list
CVCL_E7UN lacks derived-from-site-list
CVCL_A0LF lacks derived-from-site-list
CVCL_A0LF lacks derived-from-site-list
CVCL_LF98 lacks derived-from-site-list
CVCL_LF98 lacks derived-from-site-list
CVCL_B4K3 lacks derived-from-site-list
CVCL_B4K3 lacks derived-from-site-list
CVCL_B4K4 lacks derived-from-site-list
CVCL_B4K4 lacks derived-from-site-list
CVCL_VP96 lacks derived-from-site-list
CVCL_VP96 lacks derived-from-site-list
CVCL_B4KF lacks derived-from-site-list
CVCL_B4KF lacks derived-from-site-list
CVCL_B4KK lacks derived-from-site-list
CVCL_B4KK lacks derived-from-site-list
CVCL_4Z08 lacks derived-from-site-list
CVCL_4Z08 lacks derived-from-site-list
CVCL_4Z09 lacks derived-from-site-list
CVCL_4Z09 lacks derived-from-site-list
CVCL_4Z10 lacks derived-from-site-list
CVCL_4Z10 lacks derived-from-site-list
CVCL_T326 lacks derived-from-site-list
CVCL_T326 lacks derived-from-site-list
CVCL_T327 lacks derived-from-site-list
CVCL_T327 lacks derived-from-site-list
CVCL_T328 lacks derived-from-site-list
CVCL_T328 lacks derived-from-site-list
CVCL_5V13 lacks derived-from-site-list
CVCL_5V13 lacks derived-from-site-list
CVCL_5V14 lacks derived-from-site-list
CVCL_5V14 lacks derived-from-site-list
CVCL_X042 lacks derived-from-site-list
CVCL_X042 lacks derived-from-site-list
CVCL_X043 lacks derived-from-site-list
CVCL_X043 lacks derived-from-site-list
CVCL_5V16 lacks derived-from-site-list
CVCL_5V16 lacks derived-from-site-list
CVCL_RL40 lacks derived-from-site-list
CVCL_RL40 lacks derived-from-site-list
CVCL_D3YZ lacks derived-from-site-list
CVCL_D3YZ lacks derived-from-site-list
CVCL_RW69 lacks derived-from-site-list
CVCL_RW69 lacks derived-from-site-list
CVCL_8045 lacks derived-from-site-list
CVCL_8045 lacks derived-from-site-list
CVCL_RW70 lacks derived-from-site-list
CVCL_RW70 lacks derived-from-site-list
CVCL_WY47 lacks derived-from-site-list
CVCL_WY47 lacks derived-from-site-list
CVCL_VP99 lacks derived-from-site-list
CVCL_VP99 lacks derived-from-site-list
CVCL_U797 lacks derived-from-site-list
CVCL_U797 lacks derived-from-site-list
CVCL_UU21 lacks derived-from-site-list
CVCL_UU21 lacks derived-from-site-list
CVCL_UU24 lacks derived-from-site-list
CVCL_UU24 lacks derived-from-site-list
CVCL_UU42 lacks derived-from-site-list
CVCL_UU42 lacks derived-from-site-list
CVCL_9975 lacks derived-from-site-list
CVCL_9975 lacks derived-from-site-list
CVCL_2407 lacks derived-from-site-list
CVCL_2407 lacks derived-from-site-list
CVCL_VQ00 lacks derived-from-site-list
CVCL_VQ00 lacks derived-from-site-list
CVCL_1143 lacks derived-from-site-list
CVCL_1143 lacks derived-from-site-list
CVCL_1144 lacks derived-from-site-list
CVCL_1144 lacks derived-from-site-list
CVCL_1145 lacks derived-from-site-list
CVCL_1145 lacks derived-from-site-list
CVCL_DH62 lacks derived-from-site-list
CVCL_DH62 lacks derived-from-site-list
CVCL_DH63 lacks derived-from-site-list
CVCL_DH63 lacks derived-from-site-list
CVCL_H604 lacks derived-from-site-list
CVCL_H604 lacks derived-from-site-list
CVCL_H607 lacks derived-from-site-list
CVCL_H607 lacks derived-from-site-list
CVCL_H608 lacks derived-from-site-list
CVCL_H608 lacks derived-from-site-list
CVCL_H945 lacks derived-from-site-list
CVCL_H945 lacks derived-from-site-list
CVCL_H946 lacks derived-from-site-list
CVCL_H946 lacks derived-from-site-list
CVCL_B4KM lacks derived-from-site-list
CVCL_B4KM lacks derived-from-site-list
CVCL_B4KN lacks derived-from-site-list
CVCL_B4KN lacks derived-from-site-list
CVCL_H944 lacks derived-from-site-list
CVCL_H944 lacks derived-from-site-list
CVCL_B4KP lacks derived-from-site-list
CVCL_B4KP lacks derived-from-site-list
CVCL_B4KQ lacks derived-from-site-list
CVCL_B4KQ lacks derived-from-site-list
CVCL_H943 lacks derived-from-site-list
CVCL_H943 lacks derived-from-site-list
CVCL_B4KG lacks derived-from-site-list
CVCL_B4KG lacks derived-from-site-list
CVCL_W869 lacks derived-from-site-list
CVCL_W869 lacks derived-from-site-list
CVCL_DH67 lacks derived-from-site-list
CVCL_DH67 lacks derived-from-site-list
CVCL_W870 lacks derived-from-site-list
CVCL_W870 lacks derived-from-site-list
CVCL_W871 lacks derived-from-site-list
CVCL_W871 lacks derived-from-site-list
CVCL_W872 lacks derived-from-site-list
CVCL_W872 lacks derived-from-site-list
CVCL_DH68 lacks derived-from-site-list
CVCL_DH68 lacks derived-from-site-list
CVCL_DH69 lacks derived-from-site-list
CVCL_DH69 lacks derived-from-site-list
CVCL_DH70 lacks derived-from-site-list
CVCL_DH70 lacks derived-from-site-list
CVCL_DH71 lacks derived-from-site-list
CVCL_DH71 lacks derived-from-site-list
CVCL_DH72 lacks derived-from-site-list
CVCL_DH72 lacks derived-from-site-list
CVCL_DG37 lacks derived-from-site-list
CVCL_DG37 lacks derived-from-site-list
CVCL_DH73 lacks derived-from-site-list
CVCL_DH73 lacks derived-from-site-list
CVCL_DH74 lacks derived-from-site-list
CVCL_DH74 lacks derived-from-site-list
CVCL_DH75 lacks derived-from-site-list
CVCL_DH75 lacks derived-from-site-list
CVCL_DH76 lacks derived-from-site-list
CVCL_DH76 lacks derived-from-site-list
CVCL_DH66 lacks derived-from-site-list
CVCL_DH66 lacks derived-from-site-list
CVCL_DH65 lacks derived-from-site-list
CVCL_DH65 lacks derived-from-site-list
CVCL_DH64 lacks derived-from-site-list
CVCL_DH64 lacks derived-from-site-list
CVCL_VU93 lacks derived-from-site-list
CVCL_VU93 lacks derived-from-site-list
CVCL_9V17 lacks derived-from-site-list
CVCL_9V17 lacks derived-from-site-list
CVCL_9V18 lacks derived-from-site-list
CVCL_9V18 lacks derived-from-site-list
CVCL_9V00 lacks derived-from-site-list
CVCL_9V00 lacks derived-from-site-list
CVCL_F874 lacks derived-from-site-list
CVCL_F874 lacks derived-from-site-list
CVCL_F876 lacks derived-from-site-list
CVCL_F876 lacks derived-from-site-list
CVCL_F877 lacks derived-from-site-list
CVCL_F877 lacks derived-from-site-list
CVCL_F878 lacks derived-from-site-list
CVCL_F878 lacks derived-from-site-list
CVCL_ZL71 lacks derived-from-site-list
CVCL_ZL71 lacks derived-from-site-list
CVCL_6624 lacks derived-from-site-list
CVCL_6624 lacks derived-from-site-list
CVCL_6625 lacks derived-from-site-list
CVCL_6625 lacks derived-from-site-list
CVCL_F879 lacks derived-from-site-list
CVCL_F879 lacks derived-from-site-list
CVCL_ZL72 lacks derived-from-site-list
CVCL_ZL72 lacks derived-from-site-list
CVCL_ZL73 lacks derived-from-site-list
CVCL_ZL73 lacks derived-from-site-list
CVCL_ZL74 lacks derived-from-site-list
CVCL_ZL74 lacks derived-from-site-list
CVCL_F880 lacks derived-from-site-list
CVCL_F880 lacks derived-from-site-list
CVCL_F881 lacks derived-from-site-list
CVCL_F881 lacks derived-from-site-list
CVCL_F882 lacks derived-from-site-list
CVCL_F882 lacks derived-from-site-list
CVCL_IS49 lacks derived-from-site-list
CVCL_IS49 lacks derived-from-site-list
CVCL_ZL75 lacks derived-from-site-list
CVCL_ZL75 lacks derived-from-site-list
CVCL_ZL76 lacks derived-from-site-list
CVCL_ZL76 lacks derived-from-site-list
CVCL_ZL77 lacks derived-from-site-list
CVCL_ZL77 lacks derived-from-site-list
CVCL_F883 lacks derived-from-site-list
CVCL_F883 lacks derived-from-site-list
CVCL_ZL78 lacks derived-from-site-list
CVCL_ZL78 lacks derived-from-site-list
CVCL_IS50 lacks derived-from-site-list
CVCL_IS50 lacks derived-from-site-list
CVCL_ZL79 lacks derived-from-site-list
CVCL_ZL79 lacks derived-from-site-list
CVCL_F884 lacks derived-from-site-list
CVCL_F884 lacks derived-from-site-list
CVCL_F885 lacks derived-from-site-list
CVCL_F885 lacks derived-from-site-list
CVCL_F886 lacks derived-from-site-list
CVCL_F886 lacks derived-from-site-list
CVCL_F887 lacks derived-from-site-list
CVCL_F887 lacks derived-from-site-list
CVCL_ZL80 lacks derived-from-site-list
CVCL_ZL80 lacks derived-from-site-list
CVCL_ZL81 lacks derived-from-site-list
CVCL_ZL81 lacks derived-from-site-list
CVCL_F888 lacks derived-from-site-list
CVCL_F888 lacks derived-from-site-list
CVCL_ZL82 lacks derived-from-site-list
CVCL_ZL82 lacks derived-from-site-list
CVCL_F889 lacks derived-from-site-list
CVCL_F889 lacks derived-from-site-list
CVCL_F890 lacks derived-from-site-list
CVCL_F890 lacks derived-from-site-list
CVCL_IS51 lacks derived-from-site-list
CVCL_IS51 lacks derived-from-site-list
CVCL_ZL83 lacks derived-from-site-list
CVCL_ZL83 lacks derived-from-site-list
CVCL_IS52 lacks derived-from-site-list
CVCL_IS52 lacks derived-from-site-list
CVCL_6627 lacks derived-from-site-list
CVCL_6627 lacks derived-from-site-list
CVCL_IS53 lacks derived-from-site-list
CVCL_IS53 lacks derived-from-site-list
CVCL_F891 lacks derived-from-site-list
CVCL_F891 lacks derived-from-site-list
CVCL_IS54 lacks derived-from-site-list
CVCL_IS54 lacks derived-from-site-list
CVCL_F892 lacks derived-from-site-list
CVCL_F892 lacks derived-from-site-list
CVCL_IS55 lacks derived-from-site-list
CVCL_IS55 lacks derived-from-site-list
CVCL_IS56 lacks derived-from-site-list
CVCL_IS56 lacks derived-from-site-list
CVCL_F893 lacks derived-from-site-list
CVCL_F893 lacks derived-from-site-list
CVCL_IS57 lacks derived-from-site-list
CVCL_IS57 lacks derived-from-site-list
CVCL_F895 lacks derived-from-site-list
CVCL_F895 lacks derived-from-site-list
CVCL_F896 lacks derived-from-site-list
CVCL_F896 lacks derived-from-site-list
CVCL_IS58 lacks derived-from-site-list
CVCL_IS58 lacks derived-from-site-list
CVCL_F897 lacks derived-from-site-list
CVCL_F897 lacks derived-from-site-list
CVCL_F899 lacks derived-from-site-list
CVCL_F899 lacks derived-from-site-list
CVCL_F900 lacks derived-from-site-list
CVCL_F900 lacks derived-from-site-list
CVCL_F901 lacks derived-from-site-list
CVCL_F901 lacks derived-from-site-list
CVCL_IS59 lacks derived-from-site-list
CVCL_IS59 lacks derived-from-site-list
CVCL_F902 lacks derived-from-site-list
CVCL_F902 lacks derived-from-site-list
CVCL_IS60 lacks derived-from-site-list
CVCL_IS60 lacks derived-from-site-list
CVCL_IS61 lacks derived-from-site-list
CVCL_IS61 lacks derived-from-site-list
CVCL_F903 lacks derived-from-site-list
CVCL_F903 lacks derived-from-site-list
CVCL_IS62 lacks derived-from-site-list
CVCL_IS62 lacks derived-from-site-list
CVCL_IS63 lacks derived-from-site-list
CVCL_IS63 lacks derived-from-site-list
CVCL_F904 lacks derived-from-site-list
CVCL_F904 lacks derived-from-site-list
CVCL_F905 lacks derived-from-site-list
CVCL_F905 lacks derived-from-site-list
CVCL_VU95 lacks derived-from-site-list
CVCL_VU95 lacks derived-from-site-list
CVCL_X045 lacks derived-from-site-list
CVCL_X045 lacks derived-from-site-list
CVCL_F730 lacks derived-from-site-list
CVCL_F730 lacks derived-from-site-list
CVCL_9V01 lacks derived-from-site-list
CVCL_9V01 lacks derived-from-site-list
CVCL_C544 lacks derived-from-site-list
CVCL_C544 lacks derived-from-site-list
CVCL_C545 lacks derived-from-site-list
CVCL_C545 lacks derived-from-site-list
CVCL_C546 lacks derived-from-site-list
CVCL_C546 lacks derived-from-site-list
CVCL_C547 lacks derived-from-site-list
CVCL_C547 lacks derived-from-site-list
CVCL_C548 lacks derived-from-site-list
CVCL_C548 lacks derived-from-site-list
CVCL_A5AK lacks derived-from-site-list
CVCL_A5AK lacks derived-from-site-list
CVCL_Y457 lacks derived-from-site-list
CVCL_Y457 lacks derived-from-site-list
CVCL_C497 lacks derived-from-site-list
CVCL_C497 lacks derived-from-site-list
CVCL_C498 lacks derived-from-site-list
CVCL_C498 lacks derived-from-site-list
CVCL_C499 lacks derived-from-site-list
CVCL_C499 lacks derived-from-site-list
CVCL_D345 lacks derived-from-site-list
CVCL_D345 lacks derived-from-site-list
CVCL_LG05 lacks derived-from-site-list
CVCL_LG05 lacks derived-from-site-list
CVCL_LG06 lacks derived-from-site-list
CVCL_LG06 lacks derived-from-site-list
CVCL_D353 lacks derived-from-site-list
CVCL_D353 lacks derived-from-site-list
CVCL_IV49 lacks derived-from-site-list
CVCL_IV49 lacks derived-from-site-list
CVCL_UM75 lacks derived-from-site-list
CVCL_UM75 lacks derived-from-site-list
CVCL_UM87 lacks derived-from-site-list
CVCL_UM87 lacks derived-from-site-list
CVCL_6G42 lacks derived-from-site-list
CVCL_6G42 lacks derived-from-site-list
CVCL_UM79 lacks derived-from-site-list
CVCL_UM79 lacks derived-from-site-list
CVCL_UM80 lacks derived-from-site-list
CVCL_UM80 lacks derived-from-site-list
CVCL_LK65 lacks derived-from-site-list
CVCL_LK65 lacks derived-from-site-list
CVCL_UM81 lacks derived-from-site-list
CVCL_UM81 lacks derived-from-site-list
CVCL_S561 lacks derived-from-site-list
CVCL_S561 lacks derived-from-site-list
CVCL_S562 lacks derived-from-site-list
CVCL_S562 lacks derived-from-site-list
CVCL_S563 lacks derived-from-site-list
CVCL_S563 lacks derived-from-site-list
CVCL_S564 lacks derived-from-site-list
CVCL_S564 lacks derived-from-site-list
CVCL_J075 lacks derived-from-site-list
CVCL_J075 lacks derived-from-site-list
CVCL_V706 lacks derived-from-site-list
CVCL_V706 lacks derived-from-site-list
CVCL_9Z02 lacks derived-from-site-list
CVCL_9Z02 lacks derived-from-site-list
CVCL_3317 lacks derived-from-site-list
CVCL_3317 lacks derived-from-site-list
CVCL_2256 lacks derived-from-site-list
CVCL_2256 lacks derived-from-site-list
CVCL_N697 lacks derived-from-site-list
CVCL_N697 lacks derived-from-site-list
CVCL_R695 lacks derived-from-site-list
CVCL_R695 lacks derived-from-site-list
CVCL_S047 lacks derived-from-site-list
CVCL_S047 lacks derived-from-site-list
CVCL_S077 lacks derived-from-site-list
CVCL_S077 lacks derived-from-site-list
CVCL_1036 lacks derived-from-site-list
CVCL_1036 lacks derived-from-site-list
CVCL_UM82 lacks derived-from-site-list
CVCL_UM82 lacks derived-from-site-list
CVCL_S566 lacks derived-from-site-list
CVCL_S566 lacks derived-from-site-list
CVCL_UM83 lacks derived-from-site-list
CVCL_UM83 lacks derived-from-site-list
CVCL_UM84 lacks derived-from-site-list
CVCL_UM84 lacks derived-from-site-list
CVCL_S567 lacks derived-from-site-list
CVCL_S567 lacks derived-from-site-list
CVCL_ZZ48 lacks derived-from-site-list
CVCL_ZZ48 lacks derived-from-site-list
CVCL_W875 lacks derived-from-site-list
CVCL_W875 lacks derived-from-site-list
CVCL_C6NK lacks derived-from-site-list
CVCL_C6NK lacks derived-from-site-list
CVCL_S856 lacks derived-from-site-list
CVCL_S856 lacks derived-from-site-list
CVCL_W876 lacks derived-from-site-list
CVCL_W876 lacks derived-from-site-list
CVCL_S857 lacks derived-from-site-list
CVCL_S857 lacks derived-from-site-list
CVCL_W879 lacks derived-from-site-list
CVCL_W879 lacks derived-from-site-list
CVCL_C6NJ lacks derived-from-site-list
CVCL_C6NJ lacks derived-from-site-list
CVCL_W877 lacks derived-from-site-list
CVCL_W877 lacks derived-from-site-list
CVCL_DH60 lacks derived-from-site-list
CVCL_DH60 lacks derived-from-site-list
CVCL_DH61 lacks derived-from-site-list
CVCL_DH61 lacks derived-from-site-list
CVCL_C6NL lacks derived-from-site-list
CVCL_C6NL lacks derived-from-site-list
CVCL_W878 lacks derived-from-site-list
CVCL_W878 lacks derived-from-site-list
CVCL_Y045 lacks derived-from-site-list
CVCL_Y045 lacks derived-from-site-list
CVCL_H762 lacks derived-from-site-list
CVCL_H762 lacks derived-from-site-list
CVCL_Y048 lacks derived-from-site-list
CVCL_Y048 lacks derived-from-site-list
CVCL_Y050 lacks derived-from-site-list
CVCL_Y050 lacks derived-from-site-list
CVCL_H763 lacks derived-from-site-list
CVCL_H763 lacks derived-from-site-list
CVCL_X163 lacks derived-from-site-list
CVCL_X163 lacks derived-from-site-list
CVCL_X164 lacks derived-from-site-list
CVCL_X164 lacks derived-from-site-list
CVCL_X165 lacks derived-from-site-list
CVCL_X165 lacks derived-from-site-list
CVCL_GR51 lacks derived-from-site-list
CVCL_GR51 lacks derived-from-site-list
CVCL_C682 lacks derived-from-site-list
CVCL_C682 lacks derived-from-site-list
CVCL_A648 lacks derived-from-site-list
CVCL_A648 lacks derived-from-site-list
CVCL_C672 lacks derived-from-site-list
CVCL_C672 lacks derived-from-site-list
CVCL_F250 lacks derived-from-site-list
CVCL_F250 lacks derived-from-site-list
CVCL_C680 lacks derived-from-site-list
CVCL_C680 lacks derived-from-site-list
CVCL_C668 lacks derived-from-site-list
CVCL_C668 lacks derived-from-site-list
CVCL_QY56 lacks derived-from-site-list
CVCL_QY56 lacks derived-from-site-list
CVCL_WG89 lacks derived-from-site-list
CVCL_WG89 lacks derived-from-site-list
CVCL_W874 lacks derived-from-site-list
CVCL_W874 lacks derived-from-site-list
CVCL_S855 lacks derived-from-site-list
CVCL_S855 lacks derived-from-site-list
CVCL_V409 lacks derived-from-site-list
CVCL_V409 lacks derived-from-site-list
CVCL_AT85 lacks derived-from-site-list
CVCL_AT85 lacks derived-from-site-list

## Depmap
This provides all the cell lines and expression data (mostly cancer cell lines)

DepMap API exploration: https://depmap.org/portal/api/

In [6]:
url_depmap = "https://depmap.org/portal/api/download/files"

save_dir_filters = 'input/filters'
os.makedirs(save_dir_filters, exist_ok=True)

In [7]:
r = requests.get(url_depmap)
files_df = pd.read_csv(StringIO(r.text))  #This gives you all the downloadable files

### Model.csv

In [8]:
filtered_df = (
    files_df[files_df['filename'].str.contains('Model.csv', case=False, na=False)]
    .sort_values('release_date', ascending=False)
)

filtered_df

,release,release_date,filename,url,md5_hash
44,DepMap Public 25Q3,2025-09-25,Model.csv,https://storage.googleapis.com/depmap-external...,af4472ab734ea3aec974d992b504c7e5
122,DepMap Public 25Q2,2025-06-27,Model.csv,https://storage.googleapis.com/depmap-external...,9f7b51859a22c6fbe4c8cce43ae4bdf5
221,DepMap Public 24Q4,2024-12-16,Model.csv,https://ndownloader.figshare.com/files/51065297,675210d17675f3517b0ce39a3c274f16
294,DepMap Public 24Q2,2024-05-22,Model.csv,https://ndownloader.figshare.com/files/46489732,e5b60d1ce7636542d93f45494019eded
350,DepMap Public 23Q4,2023-11-20,Model.csv,https://ndownloader.figshare.com/files/43346895,c14f90f02609b9507c8b31e6d5db309b
399,DepMap Public 23Q2,2023-05-08,Model.csv,https://ndownloader.figshare.com/files/40448834,05edfe0f5e687d5b55e5affb17e8545f

In [9]:
model_url = filtered_df.iloc[0]['url']

r = requests.get(model_url, stream=True)

save_dir_model_csv = os.path.join(save_dir_filters, 'Model.csv')
with open(save_dir_model_csv, 'wb') as f:
    for chunk in r.iter_content(chunk_size=8192):
        f.write(chunk)

model_df = pd.read_csv(save_dir_model_csv)
print('Model.csv has {} cell lines'.format(len(set(model_df['StrippedCellLineName']))))

Model.csv has 2132 cell lines

### Expression dataset

In [10]:
filtered_df = (
    files_df[files_df['filename'].str.contains('ExpressionProteinCodingGenes', case=False, na=False)]
    .sort_values('release_date', ascending=False)
)

filtered_df

,release,release_date,filename,url,md5_hash
139,DepMap Public 25Q2,2025-06-27,OmicsExpressionProteinCodingGenesTPMLogp1.csv,https://storage.googleapis.com/depmap-external...,f47da0b6f8f3bbd4fe62e272e53bba4f
140,DepMap Public 25Q2,2025-06-27,OmicsExpressionProteinCodingGenesTPMLogp1Stran...,https://storage.googleapis.com/depmap-external...,79810ff3a98b283e8500180e8f8b6e7e
189,DepMap Public 24Q4,2024-12-16,OmicsExpressionProteinCodingGenesTPMLogp1.csv,https://ndownloader.figshare.com/files/51065489,71794802b750ce77c422dad0720a40af
190,DepMap Public 24Q4,2024-12-16,OmicsExpressionProteinCodingGenesTPMLogp1Batch...,https://ndownloader.figshare.com/files/51065492,afefd19098154a62972eb975a55a36c9
191,DepMap Public 24Q4,2024-12-16,OmicsExpressionProteinCodingGenesTPMLogp1Stran...,https://ndownloader.figshare.com/files/51065495,2426172ba8da8760bfc9b477a1c90843
262,DepMap Public 24Q2,2024-05-22,OmicsExpressionProteinCodingGenesTPMLogp1.csv,https://ndownloader.figshare.com/files/46490878,f00c434db50d811544ac4d047003979f
263,DepMap Public 24Q2,2024-05-22,OmicsExpressionProteinCodingGenesTPMLogp1Batch...,https://ndownloader.figshare.com/files/46493230,2078593f44c851aa9668655e5521debe
264,DepMap Public 24Q2,2024-05-22,OmicsExpressionProteinCodingGenesTPMLogp1Stran...,https://ndownloader.figshare.com/files/46493242,c4eac54206a1856b464b9bfdd924dca0
328,DepMap Public 23Q4,2023-11-20,OmicsExpressionProteinCodingGenesTPMLogp1.csv,https://ndownloader.figshare.com/files/43347204,9402aa25a19279bb20a5d6cf8791a88f
379,DepMap Public 23Q2,2023-05-08,OmicsExpressionProteinCodingGenesTPMLogp1.csv,https://ndownloader.figshare.com/files/40449128,e785fe0e00f0f4fae1e7d841336970a0
428,DepMap Public 22Q4,2022-12-01,OmicsExpressionProteinCodingGenesTPMLogp1.csv,https://ndownloader.figshare.com/files/38357462,0f502b8300df0c33bc5ac260110b8ddd

In [11]:
url_expression = filtered_df.iloc[0]['url']

r = requests.get(url_expression, stream=True)

save_dir_expression_csv = os.path.join(save_dir_filters, 'OmicsExpressionProteinCodingGenesTPMLogp1.csv')
with open(save_dir_expression_csv, 'wb') as f:
    for chunk in r.iter_content(chunk_size=8192):
        f.write(chunk)

expression_df = pd.read_csv(save_dir_expression_csv)  # This will take a while since the file is pretty big

rows, cols = expression_df.shape
print(f'expression_df has {rows} cell lines (ModelID) and {cols - 1} expression data of genes')

del expression_df  #This is to save on the memory since it's too large. You can reassign it later when you need it

expression_df has 1684 cell lines (ModelID) and 19205 expression data of genes

## JASPAR
This provides all the motifs needed for fimo's motif scanning

JASPAR: https://jaspar.elixir.no/downloads/
* Go for
    * Latest release
    * `CORE PFMs` collection for experimentally validated TF binding motifs with high quality
    * `Vertebrates` as the taxonomic group
    * `Single batch file (txt)`
    * `non-redundant` removes duplicate motifs for the same TF
    * `MEME` format can be used natively with fimo

In [12]:
url_jaspar = 'https://jaspar.elixir.no/download/data/2026/CORE/JASPAR2026_CORE_vertebrates_non-redundant_pfms_meme.txt'

save_dir_jaspar = 'input/jaspar_dataset'
os.makedirs(save_dir_jaspar, exist_ok=True)

In [13]:
file_path_jaspar = os.path.join(save_dir_jaspar, url_jaspar.split('/')[-1].split('.')[0] + '_original.txt')

response = requests.get(url_jaspar)

with open(file_path_jaspar, "wb") as f:
    f.write(response.content)

print("Downloaded to:", file_path_jaspar)

Downloaded to: input/jaspar_dataset/JASPAR2026_CORE_vertebrates_non-redundant_pfms_meme_original.txt

# Generate filters

## Filter cell_lines.csv → cell_line_names

### Melanoma

In [14]:
cell_line_df_melanoma = pd.read_csv('input/cell_lines/cell_lines_melanoma.csv')

cell_line_names_melanoma = extract_cell_line_names(cell_line_df_melanoma)
cell_line_names_melanoma

[' clone-1',
 ' clone-2',
 ' strain 19-4',
 ' subline S1',
 '00.08',
 '0008',
 '01.12',
 '0112',
 '02.02',
 '0202',
 '0342 mel',
 '0342mel',
 '04.01',
 '04.07',
 '0401',
 '0407',
 '05.18',
 '0518',
 '06.04',
 '06.07',
 '0604',
 '0607',
 '07.16',
 '0716',
 '0PP20',
 '10 CM',
 '10049',
 '1007P',
 '10092',
 '10101',
 '1011',
 '1011 mel',
 '1011-MEL',
 '1011-mel',
 '1011MEL',
 '1011mel',
 '10164',
 '10170',
 '10214',
 '10222',
 '10249M',
 '10266',
 '10378',
 '10417',
 '10538',
 '10538P',
 '1061 mel',
 '1061mel',
 '1067 mel',
 '1067mel',
 '1074 mel',
 '1074-MEL',
 '1074-mel',
 '1074MEL',
 '1074mel',
 '1088',
 '1088 Mel',
 '1088 mel',
 '1088-MEL',
 '1088-mel',
 '1088MEL',
 '1088Mel',
 '1088mel',
 '10CM',
 '11 CM',
 '1102',
 '1102 mel',
 '1102-MEL',
 '1102-mel',
 '1102MEL',
 '1102mel',
 '1106 mel',
 '1106-mel',
 '1106MEL',
 '1106mel',
 '1123',
 '1123-MEL',
 '1123-mel',
 '1123MEL',
 '1123mel',
 '1141 mel',
 '1141mel',
 '1143',
 '1143 mel',
 '1143-MEL',
 '1143-mel',
 '1143MEL',
 '1143mel',
 '1173-MEL',
 '1173-mel',
 '1173MEL',
 '1173mel',
 '1174 mel',
 '1174-MEL',
 '1174-mel',
 '1174MEL',
 '1174mel',
 '1180-MEL',
 '1180-mel',
 '1180MEL',
 '1180mel',
 '1182',
 '1182 mel',
 '1182-MEL',
 '1182-mel',
 '1182MEL',
 '1182mel',
 '1195',
 '1195 mel',
 '1195-MEL',
 '1195-mel',
 '1195MEL',
 '1195mel',
 '1199',
 '1199 mel',
 '1199-MEL',
 '1199-mel',
 '1199MEL',
 '1199mel',
 '11CM',
 '12.07',
 '1205 Lu',
 '1205-Lu',
 '1205Lu',
 '1207',
 '1241-mel',
 '1241mel',
 '1259-MEL',
 '1259-mel',
 '1259MEL',
 '1259mel',
 '1273 4-3',
 '1273 4-7',
 '1273 EV',
 '127343',
 '127347',
 '1273EV',
 '1278',
 '1278 mel',
 '1278-MEL',
 '1278-mel',
 '1278MEL',
 '1278mel',
 '1280',
 '1280 mel',
 '1280-MEL',
 '1280-mel',
 '1280MEL',
 '1280mel',
 '1286',
 '1286 mel',
 '1286-MEL',
 '1286-mel',
 '1286MEL',
 '1286mel',
 '1287',
 '1287 mel',
 '1287-MEL',
 '1287-mel',
 '1287MEL',
 '1287mel',
 '1290',
 '1290 mel',
 '1290-2',
 '1290-MEL',
 '1290-MEL p14',
 '1290-mel',
 '12902',
 '1290MEL',
 '1290MELp14',
 '1290mel',
 '1290p14',
 '12R5-1',
 '12R5-3',
 '12R5-5',
 '12R51',
 '12R53',
 '12R55',
 '12R8-1',
 '12R8-3',
 '12R81',
 '12R83',
 '13.03',
 '1300',
 '1300 mel',
 '1300-MEL',
 '1300-mel',
 '1300MEL',
 '1300mel',
 '1303',
 '1308-MEL',
 '1308-mel',
 '1308MEL',
 '1308mel',
 '1317',
 '1317 mel',
 '1317-MEL',
 '1317-mel',
 '1317MEL',
 '1317mel',
 '1335',
 '1335-MEL',
 '1335-mel',
 '1335MEL',
 '1335mel',
 '1338',
 '1338-MEL',
 '1338-mel',
 '1338MEL',
 '1338mel',
 '1341-P1-N1',
 '1341-P1-N2',
 '1341-P1-N3',
 '1341P1N1',
 '1341P1N2',
 '1341P1N3',
 '13443-Mel',
 '13443Mel',
 '1351-MEL',
 '1351-mel',
 '1351MEL',
 '1351mel',
 '1352',
 '1352-MEL',
 '1352-mel',
 '1352MEL',
 '1352mel',
 '1359',
 '1359 mel',
 '1359-MEL',
 '1359-mel',
 '1359MEL',
 '1359mel',
 '136-2',
 '1362',
 '1362 mel',
 '1362-MEL',
 '1362-mel',
 '1362MEL',
 '1362mel',
 '1363',
 '1363 mel',
 '1363-MEL',
 '1363-mel',
 '1363MEL',
 '1363mel',
 '1376',
 '1376 mel',
 '1376-MEL',
 '1376-mel',
 '1376MEL',
 '1376mel',
 '1383',
 '1383 mel',
 '1383-MEL',
 '1383-mel',
 '1383MEL',
 '1383mel',
 '1388',
 '1388 mel',
 '1388-MEL',
 '1388-mel',
 '1388MEL',
 '1388mel',
 '1390',
 '1390 mel',
 '1390-MEL',
 '1390-mel',
 '1390MEL',
 '1390mel',
 '13923M',
 '1402P',
 '1402R',
 '14362M',
 '14464',
 '14464M',
 '1479',
 '1479 mel',
 '1479-MEL',
 '1479-mel',
 '1479MEL',
 '1479mel',
 '1495',
 '1495 mel',
 '1495-MEL',
 '1495-mel',
 '1495MEL',
 '1495mel',
 '1520',
 '1520 mel',
 '1520-MEL',
 '1520-mel',
 '1520MEL',
 '1520mel',
 '15392',
 '15392M',
 '1568M',
 '15765 mel',
 '15765mel',
 '157d',
 '16396M',
 '16R5-2',
 '16R5-5',
 '16R52',
 '16R55',
 '16R6-2',
 '16R6-3',
 '16R6-4',
 '16R62',
 '16R63',
 '16R64',
 '1704',
 '17697M',
 '1858-MEL a',
 '1858-MEL a (Fragment)',
 '1858-MEL b',
 '1858-MEL b (Medimachine)',
 '1858-MEL c',
 '1858-MEL c (Wash)',
 '1858-mel a',
 '1858-mel b',
 '1858-mel c',
 '18588M',
 '1858MELa',
 '1858MELaFragment',
 '1858MELb',
 '1858MELbMedimachine',
 '1858MELc',
 '1858MELcWash',
 '1858mela',
 '1858melb',
 '1858melc',
 '18656',
 '18656M',
 '18732',
 '18732M',
 '19.4',
 '1936-MEL',
 '1936-MEL (Medimachine)',
 '1936-mel',
 '1936MEL',
 '1936MELMedimachine',
 '1936mel',
 '194',
 '1962-MEL',
 '1962-mel',
 '1962MEL',
 '1962mel',
 '196b',
 '1F6',
 '2048-mel',
 '2048mel',
 '20706M',
 '20842M1',
 '20842M2',
 '20842P',
 '2130 mel',
 '2130mel',
 '21545M',
 '21768M',
 '2211M',
 '224',
 '25368 mel',
 '25368mel',
 '2599T',
 '26258M',
 '263',
 '26396M',
 '26414M',
 '2669',
 '26G',
 '2710 mel',
 '2710mel',
 '289',
 '289 DPP3',
 '289 TAM6',
 '289/TAM6',
 '289DPP3',
 '289TAM6',
 '2934M',
 '3012T',
 '3072T',
 '30966M',
 '311',
 '3190T',
 '3191T',
 '31G',
 '3248T',
 '33365M',
 '35-P1-N1',
 '35-P1-N2',
 '35-P1-N3',
 '35-P2-N1',
 '35-P2-N2',
 '35-P2-N3',
 '35P1N1',
 '35P1N2',
 '35P1N3',
 '35P2N1',
 '35P2N2',
 '35P2N3',
 '3606',
 '3620',
 '3677',
 '37165 mel',
 '37165mel',
 '375',
 '3962M',
 '397',
 '397 mel',
 '397-MEL',
 '397-Mel',
 '397-mel',
 '397-mel/A31',
 '397MEL',
 '397Mel',
 '397mel',
 '397mel/A31',
 '397melA31',
 '3988M',
 '3D5 [Human melanoma]',
 '3D5Humanmelanoma',
 '4-1.10',
 "4-1.10''",
 '4022 mel',
 '4022mel',
 '4023',
 '4023M',
 '4110',
 '4143',
 '418',
 '4330 mel',
 '4330mel',
 '435.eB',
 '435.neo',
 '435eB',
 '435neo',
 '4405P',
 '4473M',
 '4478D mel',
 '4478Dmel',
 '451-LU',
 '451LU',
 '451LU BR',
 '451LUBR',
 '451Lu',
 '451Lu BR',
 '451Lu R',
 '451Lu-BR',
 '451Lu-MR',
 '451Lu-R',
 '451LuBR',
 '451LuMR',
 '451LuR',
 '453 A',
 '453 B',
 '453A',
 '453A0',
 '453B',
 '4686',
 '4686M',
 '48409 mel',
 '48409mel',
 '49318 mel',
 '49318mel',
 '4PP70',
 '4TP46',
 '501',
 '501 A',
 '501 Mel',
 '501 mel',
 '501-MEL',
 '501-mel',
 '501A',
 '501MEL',
 '501Mel',
 '501mel',
 '513 D',
 '513 E',
 '513D',
 '513E',
 '518 A1',
 '518 B',
 '518.A2',
 '518A1',
 '518A2',
 '518B',
 '526',
 '526 mel',
 '526-MEL',
 '526-mel',
 '526MEL',
 '526mel',
 '528 [Human melanoma]',
 '528Humanmelanoma',
 '530',
 '537',
 '537 MEL',
 '537 mel',
 '537-MEL',
 '537-mel',
 '537MEL',
 '537mel',
 '553',
 '553 mel',
 '553-MEL',
 '553-mel',
 '553B mel',
 '553B-mel',
 '553Bmel',
 '553MEL',
 '553mel',
 '5810P',
 '586',
 '586 MEL',
 '586 Mel',
 '586 mel',
 '586-MEL',
 '586-mel',
 '586MEL',
 '586Mel',
 '586mel',
 '6005',
 '603',
 '607B',
 '610',
 '624',
 '624 MEL',
 '624 Mel',
 '624 mel',
 '624-28',
 '624-38',
 '624-MEL',
 '624-mel',
 '624-mel/A31',
 '624.28',
 '624.28 Mel',
 '624.28-MEL',
 '624.38',
 '624.38 Mel',
 '624.38-MEL',
 '62428',
 '62428MEL',
 '62428Mel',
 '62438',
 '62438MEL',
 '62438Mel',
 '624MEL',
 '624Mel',
 '624mel',
 '624mel/A31',
 '624melA31',
 '6278',
 '634',
 '665/1',
 '665/2',
 '665/2/21',
 '6651',
 '6652',
 '665221',
 '677',
 '677 mel',
 '677-MEL',
 '677-mel',
 '677MEL',
 '677mel',
 '6854M',
 '697',
 '697 Mel',
 '697 mel',
 '697-MEL',
 '697-mel',
 '697MEL',
 '697Mel',
 '697mel',
 '6PP177',
 '7 mel',
 '729-MEL',
 '729-mel',
 '729MEL',
 '729mel',
 '731-MEL',
 '731-mel',
 '731MEL',
 '731mel',
 '78-1',
 '781',
 '793-P1-N1',
 '793-P1-N2',
 '793-P1-N3',
 '793-P2-N1',
 '793-P2-N2',
 '793-P2-N3',
 '793P1N1',
 '793P1N2',
 '793P1N3',
 '793P2N1',
 '793P2N2',
 '793P2N3',
 '798-MEL',
 '798-mel',
 '798MEL',
 '798mel',
 '7GC21',
 '7GC6',
 '7GP',
 '7GP122',
 '7Gp122',
 '7mel',
 '836',
 '836 mel',
 '836-MEL',
 '836-mel',
 '836MEL',
 '836mel',
 '865-MEL',
 '865-mel',
 '865MEL',
 '865mel',
 '875',
 '879M',
 '8823',
 '883',
 '883-MEL',
 '883-mel',
 '883MEL',
 '883mel',
 '888',
 '888 A2 Mel',
 '888 mel',
 '888-MEL',
 '888-mel',
 '888A2 mel',
 '888A2Mel',
 '888A2mel',
 '888MEL',
 '888mel',
 '894-MEL',
 '894-mel',
 '894MEL',
 '894mel',
 '8959M',
 '90.07',
 '9007',
 '92-1 [Human uveal melanoma]',
 '92-2 [Human uveal melanoma]',
 '92.1',
 '92.1-A',
 '92.1-B',
 '92.2',
 '921',
 '921A',
 '921B',
 '921Humanuvealmelanoma',
 '922',
 '9229',
 '922Humanuvealmelanoma',
 '928 MEL',
 '928 mel',
 '928-Mel',
 '928-mel',
 '928MEL',
 '928Mel',
 '928mel',
 '92_1',
 '92_2',
 '93.03',
 '93.05',
 '93.15.2',
 '9303',
 '9304',
 '9305',
 '93152',
 '938',
 '938 mel',
 '938-MEL',
 '938-mel',
 '938MEL',
 '938mel',
 '9460M',
 '95.23',
 '952-MEL',
 '952-mel',
 '9523',
 '952MEL',
 '952mel',
 '96E',
 '96L',
 '98.1',
 '981',
 '99.08',
 '9908',
 '9923',
 '9923M',
 '9923P',
 '9GP217',
 '9PP257-262',
 '9PP257262',
 '9TP180',
 'A 2058',
 'A 375',
 'A-101D',
 'A-1306',
 'A-2058',
 'A-375',
 'A-375 Human CD228',
 'A-375 Human CLDN18.2',
 'A-375 Human EGFR vIII',
 'A-375 KRAS p.G13D',
 'A-375 KRAS p.G13D-Luc2',
 'A-375 KRASG13D',
 'A-375 MEK1 p.Q56P',
 'A-375 MEK1Q56P',
 'A-375 NRAS p.Q61K',
 'A-375 NRAS p.Q61K-Luc2',
 'A-375 NRASQ61K',
 'A-375-Luc',
 'A-375.S2',
 'A-375P',
 'A-375SM',
 'A-875',
 'A02',
 'A02-JLO',
 'A02JLO',
 'A02M1',
 'A03',
 'A04',
 'A04-GEH',
 'A04GEH',
 'A04M',
 'A05',
 'A06',
 'A06-MLC',
 'A06M',
 'A06MLC',
 'A07',
 'A07-RM',
 'A07.RM',
 'A07RM',
 'A08',
 'A101D',
 'A11 [Human melanoma]',
 'A11-IC',
 'A11Humanmelanoma',
 'A11IC',
 'A11M',
 'A12',
 'A13',
 'A1306',
 'A14 [Human melanoma]',
 'A14Humanmelanoma',
 'A15 [Human melanoma]',
 'A15-BEP',
 'A1502',
 'A15BEP',
 'A15Humanmelanoma',
 'A15M2',
 'A2018',
 'A2058',
 'A2058(RFP/H2B-GFP)',
 'A2058(RFP/H2B-GFP) BrM',
 'A2058-RFP/H2B-GFP',
 'A2058-RFP/H2B-GFP BrM',
 'A2058RFPH2BGFP',
 'A2058RFPH2BGFPBrM',
 'A375',
 'A375 NRAS (Q61K/+/+)',
 'A375 NY-ESO-1 High',
 'A375 NY-ESO-1 Knockout',
 'A375 NY-ESO-1 Low',
 'A375 NY-ESO-1-/-',
 'A375 PF11',
 'A375 PLX/AZD-resistant',
 'A375 RL',
 'A375 RMR',
 'A375 SKIN CJ1',
 'A375 SKIN CJ2',
 'A375 SKIN CJ3',
 'A375 Safe Harbor Landing Pad',
 'A375 XPA-mutated clone A3',
 'A375 XPA-mutated clone A9',
 'A375 XPA-mutated clone B1',
 'A375-12R5-1',
 'A375-12R5-3',
 'A375-12R5-5',
 'A375-12R8-1',
 'A375-12R8-3',
 'A375-16R5-2',
 'A375-16R5-5',
 'A375-16R6-2',
 'A375-16R6-3',
 'A375-16R6-4',
 'A375-C5',
 'A375-C6',
 'A375-CD228',
 'A375-CJ1',
 'A375-CJ2',
 'A375-CJ3',
 'A375-CLDN18.2',
 'A375-EGFRVIII',
 'A375-ER-2',
 'A375-Fluc-Neo/eGFP-Puro',
 'A375-Fluc-Neo/hNIS-Puro',
 'A375-Fluc-Puro',
 'A375-Luc-RFP',
 'A375-Luc2',
 'A375-M',
 'A375-M1',
 'A375-M2',
 'A375-MA1',
 'A375-MA2',
 'A375-MEL',
 'A375-NTP-R',
 'A375-P',
 'A375-R',
 'A375-R1',
 'A375-RL',
 'A375-RMR',
 'A375-RMR SCH 0.25',
 'A375-S2',
 'A375-SM',
 'A375-VR [2014]',
 'A375-VR [2015]',
 'A375-eGFP-Puro',
 'A375-hNIS-Neo/eGFP-Puro',
 'A375-hNIS-Puro',
 'A375-iRFP-Neo',
 'A375-iRFP-Neo/Fluc-Puro',
 'A375-iRFP-Neo/hNIS-Puro',
 'A375-mel',
 'A375.S2',
 'A375/R',
 'A37512R51',
 'A37512R53',
 'A37512R55',
 'A37512R81',
 'A37512R83',
 'A37516R52',
 'A37516R55',
 'A37516R62',
 'A37516R63',
 'A37516R64',
 'A375C5',
 'A375C6',
 'A375CD228',
 'A375CJ1',
 'A375CJ2',
 'A375CJ3',
 'A375CLDN182',
 'A375Cl-5',
 'A375Cl5',
 'A375EGFRVIII',
 'A375ER2',
 'A375FlucNeoeGFPPuro',
 'A375FlucNeohNISPuro',
 'A375FlucPuro',
 'A375HumanCD228',
 'A375HumanCLDN182',
 'A375HumanEGFRvIII',
 'A375KRASG13D',
 'A375KRASpG13D',
 'A375KRASpG13DLuc2',
 'A375Luc',
 'A375Luc2',
 'A375LucRFP',
 'A375M',
 'A375M1',
 'A375M2',
 'A375MA1',
 'A375MA2',
 'A375MEK1Q56P',
 'A375MEK1pQ56P',
 'A375MEL',
 'A375NRASQ61K',
 'A375NRASpQ61K',
 'A375NRASpQ61KLuc2',
 'A375NTPR',
 'A375NYESO1',
 'A375NYESO1High',
 'A375NYESO1Knockout',
 'A375NYESO1Low',
 'A375P',
 'A375P-5',
 'A375P-beta6/puro',
 'A375P-puro',
 'A375P5',
 'A375PF11',
 'A375PLXAZDresistant',
 'A375Pbeta6puro',
 'A375Ppuro',
 'A375R',
 'A375R1',
 'A375RL',
 'A375RMR',
 'A375RMRSCH025',
 'A375S1',
 'A375S2',
 'A375SKINCJ1',
 'A375SKINCJ2',
 'A375SKINCJ3',
 'A375SM',
 'A375SafeHarborLandingPad',
 'A375VR2014',
 'A375VR2015',
 'A375XPAmutatedcloneA3',
 'A375XPAmutatedcloneA9',
 'A375XPAmutatedcloneB1',
 'A375eGFPPuro',
 'A375hNISNeoeGFPPuro',
 'A375hNISPuro',
 'A375iRFPNeo',
 'A375iRFPNeoFlucPuro',
 'A375iRFPNeohNISPuro',
 'A375m',
 'A375mel',
 'A375p',
 'A375s2',
 'A375sci',
 'A5',
 'A7',
 'A875',
 'AA-Mel',
 'AAMel',
 'AB-Mel',
 'ABMel',
 'AC-Mel',
 'ACMel',
 'ACN',
 'ACN/IFN-gamma',
 'ACN/neo',
 'ACNIFNgamma',
 'ACNneo',
 'AD-Mel',
 'ADMel',
 'AE-Mel',
 'AEMel',
 'AF-6',
 'AF-Mel',
 'AF6',
 'AFMel',
 'AG-Mel',
 'AGMel',
 'AH-Mel',
 'AHMel',
 'AI-Mel',
 'AIMel',
 'AJ-Mel',
 'AJMel',
 'AK-Mel',
 'AKMel',
 'AL #1',
 'AL-Mel',
 'AL1',
 'ALMel',
 'ALO-39',
 'ALO39',
 'ALVE39',
 'ALVE40',
 'AM-Mel',
 'AMMel',
 'AN',
 'AN-Mel',
 'ANAD 63',
 'ANAD-63',
 'ANAD63',
 'ANMel',
 'AO-Mel',
 'AOMel',
 'AP-1-bla A375',
 'AP-Mel',
 'AP1-bla A375',
 'AP1blaA375',
 'APMel',
 'AQ-Mel',
 'AQMel',
 'AR-Mel',
 'ARMel',
 'AS-Mel',
 'ASMel',
 'AT-Mel',
 'ATMel',
 'AU-Mel',
 'AUMA',
 'AUMel',
 'AV-Mel',
 'AVL3-MEL',
 'AVL3-Mel',
 'AVL3MEL',
 'AVL3Mel',
 'AVMel',
 'AW-Mel',
 'AWMel',
 'AX-Mel',
 'AXMel',
 'AY-Mel',
 'AYMel',
 'AZ-Mel',
 'AZMel',
 'Abcam A-375 IL13RA2 KO',
 'Abcam A-375 NT5E KO',
 ...]

### Melanoma brain metastasis (MBM)

In [15]:
df_mbm = cell_line_df_melanoma[
    cell_line_df_melanoma['organ'].str.contains('brain', case=False, na=False) &
    cell_line_df_melanoma['site_type'].str.contains('metastatic', case=False, na=False)
    ]  # These are all the melanoma that metastasizes to the brain

df_mbm = df_mbm.reset_index(drop=True)
df_mbm.to_csv('input/cell_lines/cell_lines_mbm.csv', index=False)

df_mbm.head()

,cell_line_id,cell_line_name,organ,site_type,disease,age,sex,category,species
0,CVCL_E6EY,"CCLF-KL1105T,CCLF_KL1105T,CPDM_0603X","Brain, left temporal cortex",Metastatic,Melanoma,74Y,Male,Cancer cell line,Homo sapiens (Human)
1,CVCL_E6F6,"CCLF-KL1187T,CCLF_KL1187T,CPDM_0762X","Brain, left temporal cortex",Metastatic,Melanoma,73Y,Female,Cancer cell line,Homo sapiens (Human)
2,CVCL_D3Z0,"CCLF-MELM_0026-T-B,CCLF_MELM_0026_T_B",Brain,Metastatic,Melanoma,58Y,Female,Cancer cell line,Homo sapiens (Human)
3,CVCL_X382,"COLO 297F,COLO #297,Colorado 297",Brain,Metastatic,Melanoma,76Y,Male,Cancer cell line,Homo sapiens (Human)
4,CVCL_1134,"COLO 792,COLO-792,COLO #792,COLO792,Colorado 792",Brain,Metastatic,Melanoma,62Y,Male,Cancer cell line,Homo sapiens (Human)

In [16]:
cell_line_names_mbm = extract_cell_line_names(df_mbm)
cell_line_names_mbm

['06.07',
 '0607',
 '875',
 'A-875',
 'A2018',
 'A875',
 'C8',
 'CCLF-KL1105T',
 'CCLF-KL1187T',
 'CCLF-MELM_0026-T-B',
 'CCLFKL1105T',
 'CCLFKL1187T',
 'CCLFMELM0026TB',
 'CCLF_KL1105T',
 'CCLF_KL1187T',
 'CCLF_MELM_0026_T_B',
 'COLO #297',
 'COLO #792',
 'COLO 297F',
 'COLO 792',
 'COLO-792',
 'COLO297',
 'COLO297F',
 'COLO792',
 'CPDM0603X',
 'CPDM0762X',
 'CPDM_0603X',
 'CPDM_0762X',
 'Colorado 297',
 'Colorado 792',
 'Colorado297',
 'Colorado792',
 'D5',
 'Ed141.MEL',
 'Ed141MEL',
 'HTZ 19',
 'HTZ 19-dM',
 'HTZ-19',
 'HTZ-19 dM',
 'HTZ19',
 'HTZ19dM',
 'LB3080-MELA',
 'LB3080MELA',
 'LM-MEL-24',
 'LM-MEL-45',
 'LM-MEL-7',
 'LM-MEL-71',
 'LM-MEL-77',
 'LM-MEL-8',
 'LM-Mel-24',
 'LM-Mel-45',
 'LM-Mel-7',
 'LM-Mel-71',
 'LM-Mel-77',
 'LM-Mel-8',
 'LMMEL24',
 'LMMEL45',
 'LMMEL7',
 'LMMEL71',
 'LMMEL77',
 'LMMEL8',
 'LMMel24',
 'LMMel45',
 'LMMel7',
 'LMMel71',
 'LMMel77',
 'LMMel8',
 'Ludwig Melbourne-MELanoma-24',
 'Ludwig Melbourne-MELanoma-45',
 'Ludwig Melbourne-MELanoma-7',
 'Ludwig Melbourne-MELanoma-71',
 'Ludwig Melbourne-MELanoma-77',
 'Ludwig Melbourne-MELanoma-8',
 'LudwigMelbourneMELanoma24',
 'LudwigMelbourneMELanoma45',
 'LudwigMelbourneMELanoma7',
 'LudwigMelbourneMELanoma71',
 'LudwigMelbourneMELanoma77',
 'LudwigMelbourneMELanoma8',
 'M970109',
 'MEL06.07',
 'MEL0607',
 'MUG Mel1',
 'MUG-MEL1-C8',
 'MUG-MEL1-D5',
 'MUG-Mel1',
 'MUG-Mel1 C8',
 'MUG-Mel1 D5',
 'MUG-Mel1 clone C8',
 'MUG-Mel1 clone D5',
 'MUGMEL1C8',
 'MUGMEL1D5',
 'MUGMel1',
 'MUGMel1C8',
 'MUGMel1D5',
 'MUGMel1cloneC8',
 'MUGMel1cloneD5',
 'Ma-Mel 45a',
 'Ma-Mel-114',
 'Ma-Mel-45A',
 'Ma-Mel-45a',
 'Ma-Mel_45A',
 'MaMel114',
 'MaMel45A',
 'MaMel45a',
 'Medical University of Graz-Melanoma 1',
 'Medical University of Graz-Melanoma 1 clone C8',
 'Medical University of Graz-Melanoma 1 clone D5',
 'MedicalUniversityofGrazMelanoma1',
 'MedicalUniversityofGrazMelanoma1cloneC8',
 'MedicalUniversityofGrazMelanoma1cloneD5',
 'Mel 06.07',
 'Mel0607',
 'NYU09-085',
 'NYU09085',
 'RVH 421',
 'RVH-421',
 'RVH-421 Dab-R',
 'RVH-421rPLX4720(10muM)',
 'RVH-421rPLX4720_10muM',
 'RVH421',
 'RVH421 SKIN FV1',
 'RVH421Dab',
 'RVH421DabR',
 'RVH421SKINFV1',
 'RVH421_Dab',
 'RVH421rPLX472010muM',
 'SW 690',
 'SW-690',
 'SW690',
 'TC 491',
 'TC491',
 'TXM-13',
 'TXM-18',
 'TXM-34',
 'TXM-40',
 'TXM13',
 'TXM18',
 'TXM34',
 'TXM40',
 'Tissue Culture 491',
 'TissueCulture491',
 'UCT Mel-5',
 'UCT-Mel 5',
 'UCTMel5',
 'University of Cape Town-Melanoma cell line 5',
 'UniversityofCapeTownMelanomacellline5',
 'VMM1',
 'WC00090',
 'WM 3734',
 'WM-3734',
 'WM3734',
 'YP-MEL',
 'YPMEL',
 'YUGANK',
 'YUGEN 8',
 'YUGEN-8',
 'YUGEN8']

### Uveal melanoma (UM)

In [17]:
df_uveal = cell_line_df_melanoma[
    cell_line_df_melanoma['disease'].str.contains('uvea', case=False, na=False)
]  #These are all the uveal melanoma, including the in situ and metastatic ones that can go to various locations (can be further specified)

df_uveal = df_uveal.reset_index(drop=True)
df_uveal.to_csv('input/cell_lines/cell_lines_um.csv', index=False)

df_uveal.head()

,cell_line_id,cell_line_name,organ,site_type,disease,age,sex,category,species
0,CVCL_VU92,"BB90-MEL,BB 90 MEL,DEZE",NaN,NaN,"Uveal melanoma,Uveal melanoma",Age unspecified,Male,Cancer cell line,Homo sapiens (Human)
1,CVCL_8471,C918,NaN,NaN,"Uveal melanoma,Uveal melanoma",60Y,Female,Cancer cell line,Homo sapiens (Human)
2,CVCL_C7UB,1141 mel,"Eye, uvea",In situ,"Uveal melanoma,Uveal melanoma",Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
3,CVCL_6900,"EOM-29,EOM29","Eye, uvea",In situ,"Uveal melanoma,Uveal melanoma",87Y,Male,Cancer cell line,Homo sapiens (Human)
4,CVCL_6901,"EOM-3,EOM3","Eye, uvea",In situ,"Uveal melanoma,Uveal melanoma",62Y,Male,Cancer cell line,Homo sapiens (Human)

In [18]:
cell_line_names_um = extract_cell_line_names(df_uveal)
cell_line_names_um

['1141 mel',
 '1141mel',
 '15765 mel',
 '15765mel',
 '157d',
 '196b',
 '2130 mel',
 '2130mel',
 '37165 mel',
 '37165mel',
 '4022 mel',
 '4022mel',
 '4330 mel',
 '4330mel',
 '48409 mel',
 '48409mel',
 '92-1 [Human uveal melanoma]',
 '92-2 [Human uveal melanoma]',
 '92.1',
 '92.1-A',
 '92.1-B',
 '92.2',
 '921',
 '921A',
 '921B',
 '921Humanuvealmelanoma',
 '922',
 '922Humanuvealmelanoma',
 '92_1',
 '92_2',
 'BB 90 MEL',
 'BB90-MEL',
 'BB90MEL',
 'C918',
 'DEZE',
 'EOM-29',
 'EOM-3',
 'EOM29',
 'EOM3',
 'EST128',
 'HL165',
 'IPC 211',
 'IPC 227F',
 'IPC 227e',
 'IPC 281',
 'IPC-211',
 'IPC-227E',
 'IPC-227F',
 'IPC-281',
 'IPC211',
 'IPC227E',
 'IPC227F',
 'IPC227e',
 'IPC281',
 'M619',
 'MEL 290',
 'MEL15765',
 'MEL20-06-039',
 'MEL20-06-045',
 'MEL20-07-070',
 'MEL2006039',
 'MEL2006045',
 'MEL2007070',
 'MEL202',
 'MEL270',
 'MEL285',
 'MEL290',
 'MKT-BR',
 'MKTBR',
 'MM28',
 'MM33',
 'MM66',
 'MP38',
 'MP41',
 'MP41 / GFP',
 'MP41 / Luciferase',
 'MP41 / Luciferase & GFP',
 'MP41 / RFP',
 'MP41/GFP',
 'MP41/Luciferase',
 'MP41/Luciferase-2A-GFP',
 'MP41/RFP',
 'MP41GFP',
 'MP41Luciferase',
 'MP41Luciferase2AGFP',
 'MP41LuciferaseGFP',
 'MP41RFP',
 'MP46',
 'MP65',
 'MU2',
 'MU2F',
 'MU7',
 'MU8 [Human uveal melanoma]',
 'MU8Humanuvealmelanoma',
 'MUM-2B',
 'MUM2B',
 'Mel 202',
 'Mel 270',
 'Mel 285',
 'Mel 290',
 'Mel-202',
 'Mel-270',
 'Mel-285',
 'Mel-290',
 'Mel20-06-039',
 'Mel20-06-045',
 'Mel20-07-070',
 'Mel20-08-128',
 'Mel20-09-196',
 'Mel2006039',
 'Mel2006045',
 'Mel2007070',
 'Mel2008128',
 'Mel2009196',
 'Mel202',
 'Mel270',
 'Mel285',
 'Mel290',
 'MkTBr',
 'MuM-2B',
 'MuM2B',
 'Mum2B',
 'OCM-2',
 'OCM2',
 'OM-431',
 'OM421',
 'OM431',
 'OM439',
 'OM443',
 'OM449',
 'OM464',
 'OM467',
 'OM482',
 'OMM 2-2',
 'OMM 2-3',
 'OMM 2-6',
 'OMM-1',
 'OMM-2',
 'OMM-2.3',
 'OMM-3',
 'OMM1',
 'OMM1.3',
 'OMM1.5',
 'OMM13',
 'OMM15',
 'OMM1_3',
 'OMM2',
 'OMM2.2',
 'OMM2.3',
 'OMM2.5',
 'OMM2.6',
 'OMM22',
 'OMM23',
 'OMM25',
 'OMM26',
 'OMM2_2',
 'OMM2_3',
 'OMM2_5',
 'OMM2_6',
 'OMM3',
 'Ocular Choroidal Melanoma-2',
 'OcularChoroidalMelanoma2',
 'Omm1',
 'Omm13',
 'Omm15',
 'Omm1_3',
 'Omm1_5',
 'Omm2.3',
 'Omm2.5',
 'Omm23',
 'Omm25',
 'SOM 157d',
 'SOM 196b',
 'SOM-196b',
 'SOM157d',
 'SOM196b',
 'SP 6.5',
 'SP-6.5',
 'SP-8.0',
 'SP6.5',
 'SP65',
 'SP6_5',
 'SP8.0',
 'SP80',
 'T105',
 'T122',
 'T127',
 'T130',
 'T142',
 'T143',
 'TJU-UM001',
 'TJU-UM001-tdTomato',
 'TJU-UM003',
 'TJU-UM004',
 'TJUUM001',
 'TJUUM001tdTomato',
 'TJUUM003',
 'TJUUM004',
 'TP17',
 'TP31',
 'Thomas Jefferson University-Uveal Melanoma 001',
 'Thomas Jefferson University-Uveal Melanoma 003',
 'Thomas Jefferson University-Uveal Melanoma 004',
 'ThomasJeffersonUniversityUvealMelanoma001',
 'ThomasJeffersonUniversityUvealMelanoma003',
 'ThomasJeffersonUniversityUvealMelanoma004',
 'UM001',
 'UM001-tdTomato',
 'UM001tdTomato',
 'UM003',
 'UM004',
 'UMT2',
 'UMT26',
 'UMT33',
 'UMT42',
 'UPMD-1',
 'UPMD-2',
 'UPMD1',
 'UPMD2',
 'UPMM-1',
 'UPMM-2',
 'UPMM-3',
 'UPMM-4',
 'UPMM1',
 'UPMM2',
 'UPMM3',
 'UPMM4',
 'Uveal Melanoma Tubingen 2',
 'Uveal Melanoma Tubingen 26',
 'Uveal Melanoma Tubingen 33',
 'Uveal Melanoma Tubingen 42',
 'Uveal Primary Melanoma with Disomy-3 1',
 'Uveal Primary Melanoma with Disomy-3 2',
 'Uveal Primary Melanoma with Monosomy-3 1',
 'Uveal Primary Melanoma with Monosomy-3 2',
 'Uveal Primary Melanoma with Monosomy-3 3',
 'Uveal Primary Melanoma with Monosomy-3 4',
 'UvealMelanomaTubingen2',
 'UvealMelanomaTubingen26',
 'UvealMelanomaTubingen33',
 'UvealMelanomaTubingen42',
 'UvealPrimaryMelanomawithDisomy31',
 'UvealPrimaryMelanomawithDisomy32',
 'UvealPrimaryMelanomawithMonosomy31',
 'UvealPrimaryMelanomawithMonosomy32',
 'UvealPrimaryMelanomawithMonosomy33',
 'UvealPrimaryMelanomawithMonosomy34',
 'V+B2',
 'V+D9H',
 'V-C10',
 'V-D9',
 'VB2',
 'VC10',
 'VD9',
 'VD9H',
 'VUP',
 'VUP 1',
 'VUP-1',
 'VUP-1 V+B2',
 'VUP-1 V+D9H',
 'VUP-1 V-C10',
 'VUP-1 V-D9',
 'VUP1',
 'VUP15',
 'VUP1VB2',
 'VUP1VC10',
 'VUP1VD9',
 'VUP1VD9H',
 'VUP20',
 'WM3618',
 'WM3618F',
 'WM3772',
 'WM3772F',
 'YUCRENA',
 'YUGLIDE',
 'mel-202',
 'mel202']

### Astrocyte (AC)

In [19]:
cell_line_df_ac = pd.read_csv('input/cell_lines/cell_lines_astrocyte.csv')
cell_line_df_ac.head()

,cell_line_id,cell_line_name,organ,site_type,disease,age,sex,category,species
0,CVCL_AQ52,Astro.4U,NaN,NaN,NaN,NaN,NaN,Finite cell line,Homo sapiens (Human)
1,CVCL_4U69,"HASTR/ci35,Human ASTRocyte/conditionally immor...",Brain,In situ,NaN,4M,Sex unspecified,Conditionally immortalized cell line,Homo sapiens (Human)
2,CVCL_B4IH,A206,Fetal brain,In situ,NaN,12-16FW,Sex unspecified,Transformed cell line,Homo sapiens (Human)
3,CVCL_X371,A735,Fetal brain,In situ,NaN,12-16FW,Sex unspecified,Transformed cell line,Homo sapiens (Human)
4,CVCL_E3G4,NHA E6/E7/hTERT/Ras,Brain,In situ,NaN,Age unspecified,Sex unspecified,Transformed cell line,Homo sapiens (Human)

In [20]:
cell_line_names_ac = extract_cell_line_names(cell_line_df_ac)
cell_line_names_ac

[' clone 35',
 '10B1',
 '5F4',
 'A206',
 'A735',
 'Astro.4U',
 'Astro4U',
 'HASTR/ci35',
 'HASTRci35',
 'Human ASTRocyte/conditionally immortalized',
 'HumanASTRocyteconditionallyimmortalized',
 'IM-HA',
 'IMHA',
 'IMmortalized-Human Astrocytes',
 'IMmortalizedHumanAstrocytes',
 'Msh3-/- SVG-A',
 'Msh3SVGA',
 'NHA E6/E7/hTERT/Ras',
 'NHA E6/E7/hTERT/Ras/Akt',
 'NHAE6E7hTERTRas',
 'NHAE6E7hTERTRasAkt',
 'SK-astrocyte-IDH1',
 'SK-astrocyte-IDH1-R132H',
 'SKastrocyteIDH1',
 'SKastrocyteIDH1R132H',
 'SV40 immortalized Glial cell',
 'SV40immortalizedGlialcell',
 'SVG',
 'SVG p12',
 'SVG(P12)',
 'SVG-10B1',
 'SVG-5F4',
 'SVG-A',
 'SVG-A CHMP1A null',
 'SVG-A Msh3 1.7X',
 'SVG-A Msh3-/-',
 'SVG-TH',
 'SVG10B1',
 'SVG5F4',
 'SVGA',
 'SVGACHMP1Anull',
 'SVGAMsh3',
 'SVGAMsh317X',
 'SVGP12',
 'SVGR2',
 'SVGTH',
 'SVGp12',
 'clone35']

## cell_line_names → model_id_cell_line

In [21]:
model_id_melanoma = cell_line_names_to_model_id(cell_line_names_melanoma, model_df)
model_id_mbm = cell_line_names_to_model_id(cell_line_names_mbm, model_df)
model_id_um = cell_line_names_to_model_id(cell_line_names_um, model_df)

model_id_ac = cell_line_names_to_model_id(cell_line_names_ac, model_df)

## expression_df → expression_tf_df_cell_lines
For each cell line
1. expression_df —[model_id_cell_line]→ expression_df_cell_lines
2. expression_df_cell_lines —[jaspar_tf]→ expression_tf_df_cell_lines

These 2 steps are done together to avoid consuming lots of memories

The recommended workflow is to use vanilla JASPAR to do fimo motif scanning and then use expression_tf_df_cell_lines to filter out the results

#### Obtain all TF in Jaspar dataset

In [22]:
tf_names = []

with open(file_path_jaspar) as motif_database:
    for line in motif_database:
        if line.startswith('MOTIF'):
            parts = line.strip().split()
            if len(parts) >= 3:
                tf_names.append(parts[2])  # third column is TF name

print(f'Original JASPAR dataset has {len(tf_names)} TF')

Original JASPAR dataset has 1019 TF

In [23]:
expression_df = pd.read_csv(
    'input/filters/OmicsExpressionProteinCodingGenesTPMLogp1.csv')  #This will take a while since the file is pretty big

In [24]:
# Use the common cutoff: log2(TPM+1) ≥ 1 (i.e., TPM ≥ 1) in at least 50% of cell lines. If so, it means the TF is expressed in melanoma
TPM_LOGP1_threshold = 1.0
FRACTION_REQUIRED = 0.5

In [25]:
variable_dict = {
    'melanoma': model_id_melanoma,
    'mbm': model_id_mbm,
    'um': model_id_um,
    'ac': model_id_ac
}

for key, value in variable_dict.items():
    expression_df_to_expression_tf_df_cell_lines(expression_df, value, tf_names, TPM_LOGP1_threshold, FRACTION_REQUIRED, key)

Found 449 TF from JASPAR dataset for TF expressed in specific MELANOMA cell lines
Files saved for names of TF expressed in MELANOMA cell lines
Found 447 TF from JASPAR dataset for TF expressed in specific MBM cell lines
Files saved for names of TF expressed in MBM cell lines
Found 427 TF from JASPAR dataset for TF expressed in specific UM cell lines
Files saved for names of TF expressed in UM cell lines
Found 0 TF from JASPAR dataset for TF expressed in specific AC cell lines
Files saved for names of TF expressed in AC cell lines

## jaspar —[expressed_tf_cell_line]→ jaspar_cell_line
jaspar_cell_line is not recommended for fimo scanning since it might be too narrow for such an early step, but I included the steps to generate jaspar_cell_line just in case