# Import packages

In [1]:
import os, requests
from pprint import pprint
import pandas as pd

# Custom functions

In [2]:
from tools.create_jaspar_filters import obtain_jaspar_dataset, obtain_taxonomy_id, obtain_all_cell_lines, \
    cell_lines_df_clearing

# Download original JASPAR dataset
JASPAR: https://jaspar.elixir.no/downloads/
* Go for
    * Latest release
    * `CORE PFMs` collection for experimentally validated TF binding motifs with high quality
    * `Vertebrates` as the taxonomic group
    * `Single batch file (txt)`
    * `non-redundant` removes duplicate motifs for the same TF
    * `MEME` format can be used natively with fimo

In [3]:
jaspar_url = 'https://jaspar.elixir.no/download/data/2026/CORE/JASPAR2026_CORE_vertebrates_non-redundant_pfms_meme.txt'

jaspar_save_dir = 'input/jaspar_dataset'
os.makedirs(jaspar_save_dir, exist_ok=True)

In [4]:
file_path = os.path.join(jaspar_save_dir, jaspar_url.split('/')[-1].split('.')[0] + '_original.txt')

response = requests.get(jaspar_url)

with open(file_path, "wb") as f:
    f.write(response.content)

print("Downloaded to:", file_path)

Downloaded to: input/jaspar_dataset/JASPAR2026_CORE_vertebrates_non-redundant_pfms_meme_original.txt

# Obtain specific cell lines
Same logic can be applied to other diseases for filtering

In [5]:
filter_save_dir = 'input/filters'
os.makedirs(filter_save_dir, exist_ok=True)

## Obtain all melanoma cell lines

### (Optional) Obtain all NCIt code releated to a search term
NCI EVS API fields exploration: https://evsexplore.semantics.cancer.gov/evsexplore/evsapi

In [6]:
ncit_search_term = 'melanoma'  #Seaching "melanoma" will also return results like "cutaneous melanoma"
page_size = 500  #This is for pagerization that NCIt has. It's a protection such that not all results return in 1 call but that also means you need to iterate and pool all the returns together

In [7]:
all_concepts = obtain_jaspar_dataset(ncit_search_term, page_size)

Concepts obtained: 0 to 500
Concepts obtained: 500 to 1000
Concepts obtained: 1000 to 1500
Concepts obtained: 1500 to 1642
Total NCIt code(s) retrieved for melanoma: 1642

In [8]:
pprint(all_concepts, indent=4)

[   {   'active': True,
        'code': 'C3224',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C91477',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma Pathway',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C21790',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Mouse Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C103113',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'NCI CTEP SDC Melanoma Sub-Category Terminology',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C157920',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma Surgery',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C1830',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma Theraccine',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C46091',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma Biomarker',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C2517',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Melanoma Vaccine',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C3802',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Amelanotic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C120298',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Canine Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C133089',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Hamster Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C147983',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Refractory Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C153169',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Advanced Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C159663',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Bladder Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C159665',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Urethral Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C161611',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Prostate Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C189816',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'DecisionDx-Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C190239',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Resectable Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C204888',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Volar Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C162547',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Penile Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4553',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Corneal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C27394',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Vaginal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4640',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Rectal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C114828',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Mucosal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C134773',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Gerbil Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C190746',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Iridociliary Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C205125',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Nodular Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C205129',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Dermal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C215226',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Anorectal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4228',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Regressing Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C45652',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Lung Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C165497',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Cutaneous Spitz Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C204889',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Nail Apparatus Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C48607',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Invasive Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C24155',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Mouse Gallbladder Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C54686',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma Cells Present',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C3510',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4550',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Conjunctival Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4561',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Choroid Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C5707',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Esophageal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C166399',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Sinonasal Mucosal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C48614',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Desmoplastic Neurotropic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C80046',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'B16alphaGal Melanoma Vaccine',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C8711',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Non-Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C16835',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Experimental Malignant Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C135006',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Fish Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C178441',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Ovarian Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C188067',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Jejunal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C198601',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Goat Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C204883',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Acral Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C213491',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Mediastinal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C217198',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Localized Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C37257',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Desmoplastic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C54662',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Nevoid Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C8925',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Metastatic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C104501',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma-Associated Antigen 2',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C157882',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Immunotherapy for Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C1633',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Polyvalent Melanoma Vaccine',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C166405',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Mucosal Nodular Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C171294',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Recurrent Ocular Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C172247',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Unresectable Uveal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C173335',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Refractory Uveal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C182127',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Metastatic Conjunctival Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C189817',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'DecisionDx-Uveal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C190240',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Resectable Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C213517',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Parotid Gland Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C214942',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Unresectable Conjunctival Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C214944',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Recurrent Conjunctival Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C214951',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Recurrent Acral Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C54663',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Signet Ring Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C7089',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Regressing Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C9097',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Recurrent Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C36872',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Epithelioid Melanoma Cell',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C62403',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Balloon Melanoma Cell',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4558',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Ciliary Body Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C9151',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Lentigo Maligna Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C118497',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Circulating Melanoma Cell',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C156072',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Metastatic Cutaneous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C182024',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Refractory Metastatic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C212033',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Advanced Acral Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C213201',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Conjunctival Amelanotic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C213771',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Unresectable Acral Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C215228',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Resectable Anorectal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C217197',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Localized Uveal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C48622',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Mucosal Lentiginous Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C6865',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Choroid Necrotic Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C9152',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Low-CSD Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C62400',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Large Melanoma Cell',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4358',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Eyelid Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C4639',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Anal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C5735',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Gallbladder Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C7712',
        'conceptStatus': 'DEFAULT',
        'leaf': False,
        'name': 'Uveal Melanoma',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C176904',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma-Pancreatic Cancer Syndrome',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C66753',
        'conceptStatus': 'DEFAULT',
        'leaf': True,
        'name': 'Melanoma in Precancerous Melanosis',
        'terminology': 'ncit',
        'version': '26.02d'},
    {   'active': True,
        'code': 'C5915',
        'conceptStatus': 'DEFAULT',
        'leaf': True,

In [9]:
ncit_dict = {dict['code']: dict['name'] for dict in all_concepts}  #All the other fields don't matter
pprint(ncit_dict)

{'C100054': 'Conjunctival Melanocytic Intraepithelial Lesion',
 'C101364': 'KCNMA1 wt Allele',
 'C101787': 'TIL 1383I T Cell Receptor-Transduced Autologous T Cells',
 'C102753': 'Adenovirus Encoding Tyrosinase/MART-1/MAGEA6-transduced '
            'Autologous Dendritic Cell Vaccine',
 'C10303': 'CDB Regimen',
 'C103113': 'NCI CTEP SDC Melanoma Sub-Category Terminology',
 'C103830': 'Recombinant Human Hsp110-gp100 Chaperone Complex Vaccine',
 'C103862': 'Allogeneic Irradiated Melanoma Cell Vaccine CSF470',
 'C104047': 'CTAG2 wt Allele',
 'C104492': 'BAGE Gene',
 'C104493': 'BAGE wt Allele',
 'C104494': 'B Melanoma Antigen 1',
 'C104496': 'MAGEA10 Gene',
 'C104497': 'MAGEA10 wt Allele',
 'C104498': 'Melanoma-Associated Antigen 10',
 'C104499': 'MAGEA2 Gene',
 'C104500': 'MAGEA2 wt Allele',
 'C104501': 'Melanoma-Associated Antigen 2',
 'C104509': 'MAGEA1 Gene',
 'C104510': 'MAGEA1 wt Allele',
 'C104511': 'Melanoma-Associated Antigen 1',
 'C104512': 'MAGEA4 Gene',
 'C104513': 'MAGEA4 wt Allele',
 'C104515': 'Melanoma-Associated Antigen 4',
 'C104517': 'MAGEA6 Gene',
 'C104518': 'MAGEA6 wt Allele',
 'C104519': 'Melanoma-Associated Antigen 6',
 'C104522': 'MAGEB18 wt Allele',
 'C104523': 'Melanoma-Associated Antigen B18',
 'C104525': 'MAGEC1 wt Allele',
 'C104526': 'Melanoma-Associated Antigen C1',
 'C104527': 'MAGEC2 Gene',
 'C104528': 'MAGEC2 wt Allele',
 'C104529': 'Melanoma-Associated Antigen C2',
 'C106354': 'Syntenin-1',
 'C106593': 'CD63 Antigen',
 'C107135': 'NDN wt Allele',
 'C107159': 'MART-1/gp100/Tyrosinase/MAGE-A3 Peptides-loaded Irradiated '
            'Allogeneic Plasmacytoid Dendritic Cells',
 'C107166': 'pBCAR3 Phosphopeptide-tetanus Peptide Vaccine',
 'C107167': 'pIRS2 Phosphopeptide-tetanus Peptide Vaccine',
 'C107168': 'pBCAR3/pIRS2-Phosphopeptide-tetanus Peptide Vaccine',
 'C107169': 'Allogeneic HLA-A2/4-1BB ligand-expressing Melanoma Vaccine',
 'C107423': 'MAGEB2 Gene',
 'C107425': 'MAGEB2 wt Allele',
 'C107428': 'Melanoma-Associated Antigen B2',
 'C1106': 'Fotemustine',
 'C11081': 'BOLD Regimen',
 'C1110': 'Ganglioside GD2',
 'C111020': 'Uveal Class 1 Melanoma',
 'C111021': 'Uveal Class 2 Melanoma',
 'C111022': 'Uveal Class 1a Melanoma',
 'C111023': 'Uveal Class 1b Melanoma',
 'C111024': 'Presence of Extravascular Matrix Patterns',
 'C111025': 'Extravascular Matrix Loops',
 'C111026': 'Loops Forming Networks',
 'C111028': 'Extrascleral Extension of Uveal Melanoma',
 'C111030': 'Uveal Melanoma by Gene Expression Profile',
 'C111683': 'MART-1 Reactive CD8+ T-lymphocytes',
 'C111806': 'MART1 Antibody',
 'C111900': 'Autologous Melanoma Lysate/NY-ESO-1-pulsed Autologous Dendritic '
            'Cell Vaccine',
 'C112003': 'Neoantigen-based Melanoma-Poly-ICLC Vaccine',
 'C113115': 'GPNMB wt Allele',
 'C113174': 'Autologous CT7/MAGE-A3/WT1 mRNA-Electroporated Langerhans-Type '
            'Dendritic Cells',
 'C11354': 'Peptide 946 Melanoma Vaccine/QS21',
 'C11355': 'Peptide 946 Melanoma Vaccine/QS21/Tetanus Peptide Melanoma Vaccine',
 'C113841': 'Melanoma-Associated Antigen Family',
 'C11428': "Incomplete Freund's Adjuvant/Peptide 946 Melanoma Vaccine",
 'C114828': 'Mucosal Melanoma',
 'C11494': 'Interferon Alfa/Interleukin-2 Liposome/Polyvalent Melanoma Vaccine',
 'C114978': 'MAGE-A4-specific TCR Gene-transduced Autologous T Lymphocytes '
            'TBI-1201',
 'C115157': 'MAGEA3 Antibody',
 'C1157': 'Recombinant GRO1 Protein',
 'C11571': 'GM2-KLH Vaccine/QS21',
 'C11583': "Incomplete Freund's Adjuvant/Peptide 946-Tetanus Peptide Conjugate "
           'Melanoma Vaccine',
 'C11590': 'ALVAC-hB7.1/Canarypox-hIL-12 Melanoma Vaccine',
 'C115979': 'HLA-DP0401/0402-Restricted MAGE-A3-Reactive T Cell '
            'Receptor-transduced Autologous T Cells',
 'C116017': 'Melanoma-Associated Antigen Family A',
 'C116072': 'Autologous CD8+ Melanoma Specific T Cells',
 'C11655': 'Montanide ISA-51/Peptide 946 melanoma vaccine',
 'C11656': 'Montanide ISA-51/Peptide 946-tetanus peptide conjugate melanoma '
           'vaccine',
 'C11658': 'Montanide ISA-51/Peptide 946 melanoma vaccine/Tetanus peptide '
           'melanoma vaccine',
 'C11662': 'gp100 Antigen/Montanide ISA-51/Sargramostim/Tetanus Peptide '
           'Melanoma Vaccine/Tyrosinase Peptide',
 'C116711': 'Autologous MAGE-A3-specific HLA-A*01-Restricted T Cell Receptor '
            'Gene Engineered Lymphocytes',
 'C116848': 'Anti-PRAME Immunotherapeutic GSK2302032A',
 'C116862': 'MAGE-A3/12-specific TCR Gene-transduced Autologous PBLs',
 'C11695': 'gp100 Antigen/Tetanus Peptide Melanoma Vaccine/Tyrosinase Peptide',
 'C11706': 'BCG/Polyvalent Melanoma Vaccine',
 'C117181': 'LOX IMVI',
 'C117182': 'MALME-3M',
 'C117183': 'M14',
 'C117184': 'MDA-MB-435',
 'C117188': 'SK-MEL-2',
 'C117189': 'SK-MEL-28',
 'C117190': 'SK-MEL-5',
 'C117191': 'UACC-257',
 'C117192': 'UACC-62',
 'C117226': 'MDA-N',
 'C118358': 'Exoresection',
 'C118359': 'Endoresection',
 'C118367': 'NY-ESO-1/MAGE-A4/PRAME/Survivin/SSX2-specific Autologous '
            'Cytotoxic T Lymphocytes',
 'C118497': 'Circulating Melanoma Cell',
 'C118512': 'Cutaneous Melanoma In-Transit Metastasis',
 'C118776': 'Ingenol Mebutate Gel',
 'C118828': 'Orbital Melanoma',
 'C118893': 'HMB-45',
 'C118973': 'Genetically-modified MAGE-A3-expressing MG1 Maraba Virus Vaccine',
 'C119614': 'MAGE-A3-expressing Adenovirus Type 5 Vaccine',
 'C119720': 'IFIH1 wt Allele',
 'C119721': 'Interferon-Induced Helicase C Domain-Containing Protein 1',
 'C120016': 'Lymph Node Gene Expression Signature',
 'C120129': 'NY-ESO-1/MART-1 Peptide-pulsed Dendritic Cell Vaccine',
 'C120183': 'Eltrapuldencel-T',
 'C120298': 'Canine Melanoma',
 'C122396': 'Tetravalent RNA-lipoplex Cancer Vaccine BNT111',
 'C122905': 'NGFI-A-Binding Protein 2',
 'C123428': 'Naxitamab',
 'C123649': 'MAGE-A3-specific Immunotherapeutic GSK 2132231A',
 'C123817': 'Donor-derived WT1/PRAME/NY-ESO-1/Survivin-specific T-lymphocytes',
 'C124054': 'Multi-glioblastoma-peptide-targeting Autologous Dendritic Cell '
            'Vaccine ICT-107',
 'C124236': 'Membrane-Associated Transporter Protein',
 'C124263': 'MAGEA1 Antibody',
 'C125144': 'FACT-M Questionnaire',
 'C125145': 'Have Pain at Melanoma Site Question',
 'C125151': 'Have Swelling at Melanoma Site Question',
 'C126686': 'Autologous MAGE-A10-specific HLA-A2-restricted TCR c796 '
            'Gene-engineered Lymphocytes',
 'C1269': 'TAG-72 Antigen',
 'C127125': 'NY-ESO-1/PRAME/MAGE-A3/WT-1 Peptide Vaccine',
 'C127928': 'PRAME Gene',
 'C127929': 'PRAME wt Allele',
 'C127930': 'Melanoma Antigen Preferentially Expressed in Tumors',
 'C128029': 'PRAME-targeting T-cell Receptor/Inducible Caspase 9 BPX-701',
 'C128489': 'HLA-A2-restricted Melanoma-specific Peptides Vaccine GRN-1201',
 'C128801': 'Hereditary Melanoma with CDKN2A Mutation',
 'C128892': 'Type-1 Polarized Dendritic Cell-induced Antigen-specific '
            'Autologous Cytotoxic T Lymphocytes',
 'C128952': 'Chemokine (C-X-C Motif) Ligand 1 Measurement',
 'C129313': 'Factor VII-targeting Immunoconjugate Protein ICON-1',
 'C12947': 'Sentinel Lymph Node',
 'C12984': 'Interval Lymph Node',
 'C131206': 'SAMMSON Gene',
 'C131207': 'SAMMSON wt Allele',
 'C131208': 'Survival Associated Mitochondrial Melanoma Specific Oncogenic '
            'Non-Coding RNA',
 'C131215': 'Montanide ISA-51 VG/KLH/NY-ESO-1/MART-1 Peptide Vaccine',
 'C131287': 'KLH/NY-ESO-1/MART-1 Peptide-pulsed Dendritic Cell Vaccine',
 'C131506': 'Childhood Melanoma',
 'C131619': 'MAGEA10 Positive',
 'C132656': 'Cervical Lymph Nodes and Unknown Primary Tumors TNM Finding v8',
 'C132688': 'Lip and Oral Cavity Cancer TNM Finding v8',
 'C132792': 'Nasopharyngeal Cancer TNM Finding v8',
 'C133024': 'Nasal Cavity and Paranasal Sinuses Cancer TNM Finding v8',
 'C133089': 'Hamster Melanoma',
 'C133168': 'Head and Neck Mucosal Melanoma TNM Finding v8',
 'C133169': 'Head and Neck Mucosal Melanoma Clinical TNM Finding v8',
 'C133170': 'Head and Neck Mucosal Melanoma Clinical Distant Metastasis TNM '
            'Finding v8',
 'C133171': 'Head and Neck Mucosal Melanoma cM0 TNM Finding v8',
 'C133172': 'Head and Neck Mucosal Melanoma cM1 TNM Finding v8',
 'C133173': 'Head and Neck Mucosal Melanoma Pathologic TNM Finding v8',
 'C133175': 'Head and Neck Mucosal Melanoma Pathologic Distant Metastasis TNM '
            'Finding v8',
 'C133176': 'Head and Neck Mucosal Melanoma pM1 TNM Finding v8',
 'C133177': 'Head and Neck Mucosal Melanoma Pathologic Primary Tumor TNM '
            'Finding v8',
 'C133178': 'Head and Neck Mucosal Melanoma pT3 TNM Finding v8',
 'C133179': 'Head and Neck Mucosal Melanoma pT4 TNM Finding v8',
 'C133180': 'Head and Neck Mucosal Melanoma pT4a TNM Finding v8',
 'C133181': 'Head and Neck Mucosal Melanoma pT4b TNM Finding v8',
 'C133182': 'Head and Neck Mucosal Melanoma Pathologic Regional Lymph Nodes '
            'TNM Finding v8',
 'C133183': 'Head and Neck Mucosal Melanoma pNX TNM Finding v8',
 'C133184': 'Head and Neck Mucosal Melanoma pN0 TNM Finding v8',
 'C133185': 'Head and Neck Mucosal Melanoma pN1 TNM Finding v8',
 'C133186': 'Head and Neck Mucosal Melanoma by AJCC v7 Stage',
 'C133187': 'Head and Neck Mucosal Melanoma',
 'C133504': 'Metastatic Melanoma in the Central Nervous System',
 'C133762': 'Anal Cancer TNM Finding v8',
 'C133787': 'Anal Canal Cancer by AJCC v6 and v7 Stage',
 'C133794': 'Anal Cancer by AJCC v8 Stage',
 'C133814': 'PRAME Positive',
 'C134491': 'MLANA Positive',
 'C134569': 'Horse Melanoma',
 'C134572': 'Medaka Melanoma',
 'C134575': 'Xiphophorus Melanoma',
 'C1347': 'Azimexon',
 'C134773': 'Gerbil Melanoma',
 'C135006': 'Fish Melanoma',
 'C135534': 'Autologous MAGE-A3/A6-specific TCR Gene-engineered Lymphocytes '
            'KITE-718',
 'C135574': 'MAGEA6 Positive',
 'C135575': 'MAGEA3 Positive',
 'C136283': 'Carboplatin/Nab-paclitaxel Regimen',
 'C136426': 'Anti-GD3 Antibody-drug Conjugate PF-06688992',
 'C136825': 'Cutaneous Spitz Melanocytoma',
 'C136831': 'Skin Cancer TNM Finding v8',
 'C136892': 'Cutaneous Melanoma TNM Finding v8',
 'C136893': 'Cutaneous Melanoma Clinical TNM Finding v8',
 'C136894': 'Cutaneous Melanoma Clinical Distant Metastasis TNM Finding v8',
 'C136895': 'Cutaneous Melanoma cM0 TNM Finding v8',
 'C136896': 'Cutaneous Melanoma cM1 TNM Finding v8',
 'C136897': 'Cutaneous Melanoma cM1a TNM Finding v8',
 'C136898': 'Cutaneous Melanoma cM1a(0) TNM Finding v8',
 'C136899': 'Cutaneous Melanoma cM1a(1) TNM Finding v8',
 'C136900': 'Cutaneous Melanoma cM1b TNM Finding v8',
 'C136901': 'Cutaneous Melanoma cM1b(0) TNM Finding v8',
 'C136902': 'Cutaneous Melanoma cM1b(1) TNM Finding v8',
 'C136903': 'Cutaneous Melanoma cM1c TNM Finding v8',
 'C136904': 'Cutaneous Melanoma cM1c(0) TNM Finding v8',
 'C136905': 'Cutaneous Melanoma cM1c(1) TNM Finding v8',
 'C136906': 'Cutaneous Melanoma cM1d TNM Finding v8',
 'C136907': 'Cutaneous Melanoma cM1d(0) TNM Finding v8',
 'C136908': 'Cutaneous Melanoma cM1d(1) TNM Finding v8',
 'C136909': 'Cutaneous Melanoma Clinical Regional Lymph Nodes TNM Finding v8',
 'C136910': 'Cutaneous Melanoma cNX TNM Finding v8',
 'C136911': 'Cutaneous Melanoma cN0 TNM Finding v8',
 'C136912': 'Cutaneous Melanoma cN1 TNM Finding v8',
 'C136913': 'Cutaneous Melanoma cN1b TNM Finding v8',
 'C136914': 'Cutaneous Melanoma cN1c TNM Finding v8',
 'C136915': 'Cutaneous Melanoma cN2 TNM Finding v8',
 'C136916': 'Cutaneous Melanoma cN2b TNM Finding v8',
 'C136917': 'Cutaneous Melanoma cN2c TNM Finding v8',
 'C136918': 'Cutaneous Melanoma cN3 TNM Finding v8',
 'C136919': 'Cutaneous Melanoma cN3b TNM Finding v8',
 'C136920': 'Cutaneous Melanoma cN3c TNM Finding v8',
 'C136921': 'Cutaneous Melanoma Pathologic TNM Finding v8',
 'C136922': 'Cutaneous Melanoma Pathologic Distant Metastasis TNM Finding v8',
 'C136923': 'Cutaneous Melanoma pM1 TNM Finding v8',
 'C136924': 'Cutaneous Melanoma pM1a TNM Finding v8',
 'C136925': 'Cutaneous Melanoma pM1a(0) TNM Finding v8',
 'C136926': 'Cutaneous Melanoma pM1a(1) TNM Finding v8',
 'C136927': 'Cutaneous Melanoma pM1b TNM Finding v8',
 'C136928': 'Cutaneous Melanoma pM1b(0) TNM Finding v8',
 'C136929': 'Cutaneous Melanoma pM1b(1) TNM Finding v8',
 'C136930': 'Cutaneous Melanoma pM1c TNM Finding v8',
 'C136931': 'Cutaneous Melanoma pM1c(0) TNM Finding v8',
 'C136932': 'Cutaneous Melanoma pM1c(1) TNM Finding v8',
 'C136934': 'Cutaneous Melanoma pM1d TNM Finding v8',
 'C136935': 'Cutaneous Melanoma pM1d(0) TNM Finding v8',
 'C136936': 'Cutaneous Melanoma pM1d(1) TNM Finding v8',
 'C136937': 'Cutaneous Melanoma Pathologic Primary Tumor TNM Finding v8',
 'C136938': 'Cutaneous Melanoma pTX TNM Finding v8',
 'C136939': 'Cutaneous Melanoma pT0 TNM Finding v8',
 'C136940': 'Cutaneous Melanoma pTis TNM Finding v8',
 'C136941': 'Cutaneous Melanoma pT1 TNM Finding v8',
 'C136942': 'Cutaneous Melanoma pT1a TNM Finding v8',
 'C136943': 'Cutaneous Melanoma pT1b TNM Finding v8',
 'C136944': 'Cutaneous Melanoma pT2 TNM Finding v8',
 'C136945': 'Cutaneous Melanoma pT2a TNM Finding v8',
 'C136946': 'Cutaneous Melanoma pT2b TNM Finding v8',
 'C136947': 'Cutaneous Melanoma pT3 TNM Finding v8',
 'C136948': 'Cutaneous Melanoma pT3a TNM Finding v8',
 'C136949': 'Cutaneous Melanoma pT3b TNM Finding v8',
 'C136950': 'Cutaneous Melanoma pT4 TNM Finding v8',
 'C136951': 'Cutaneous Melanoma pT4a TNM Finding v8',
 'C136952': 'Cutaneous Melanoma pT4b TNM Finding v8',
 'C136953': 'Cutaneous Melanoma Pathologic Regional Lymph Nodes TNM Finding v8',
 'C136954': 'Cutaneous Melanoma pNX TNM Finding v8',
 'C136955': 'Cutaneous Melanoma pN0 TNM Finding v8',
 'C136956': 'Cutaneous Melanoma pN1 TNM Finding v8',
 'C136957': 'Cutaneous Melanoma pN1a TNM Finding v8',
 'C136958': 'Cutaneous Melanoma pN1c TNM Finding v8',
 'C136959': 'Cutaneous Melanoma pN2 TNM Finding v8',
 'C136960': 'Cutaneous Melanoma pN2a TNM Finding v8',
 'C136961': 'Cutaneous Melanoma pN2c TNM Finding v8',
 'C136963': 'Cutaneous Melanoma pN3 TNM Finding v8',
 'C136964': 'Cutaneous Melanoma pN3a TNM Finding v8',
 'C136966': 'Cutaneous Melanoma pN3c TNM Finding v8',
 'C137645': 'Cutaneous Melanoma by AJCC v8 Stage',
 'C137646': 'Cutaneous Melanoma by AJCC v8 Clinical Stage',
 'C137647': 'Clinical Stage 0 Cutaneous Melanoma AJCC v8',
 'C137648': 'Clinical Stage I Cutaneous Melanoma AJCC v8',
 'C137649': 'Clinical Stage IA Cutaneous Melanoma AJCC v8',
 'C137650': 'Clinical Stage IB Cutaneous Melanoma AJCC v8',
 'C137651': 'Clinical Stage II Cutaneous Melanoma AJCC v8',
 'C137652': 'Clinical Stage IIA Cutaneous Melanoma AJCC v8',
 'C137653': 'Clinical Stage IIB Cutaneous Melanoma AJCC v8',
 'C137654': 'Clinical Stage IIC Cutaneous Melanoma AJCC v8',
 'C137655': 'Clinical Stage III Cutaneous Melanoma AJCC v8',
 'C137656': 'Clinical Stage IV Cutaneous Melanoma AJCC v8',
 'C137657': 'Cutaneous Melanoma by AJCC v8 Pathologic Stage',
 'C137662': 'Pathologic Stage 0 Cutaneous Melanoma AJCC v8',
 'C137663': 'Pathologic Stage I Cutaneous Melanoma AJCC v8',
 'C137664': 'Pathologic Stage IA Cutaneous Melanoma AJCC v8',
 'C137665': 'Pathologic Stage IB Cutaneous Melanoma AJCC v8',
 'C137666': 'Pathologic Stage II Cutaneous Melanoma AJCC v8',
 'C137667': 'Pathologic Stage IIA Cutaneous Melanoma AJCC v8',
 'C137668': 'Pathologic Stage IIB Cutaneous Melanoma AJCC v8',
 'C137669': 'Pathologic Stage IIC Cutaneous Melanoma AJCC v8',
 'C137670': 'Pathologic Stage III Cutaneous Melanoma AJCC v8',
 'C137671': 'Pathologic Stage IIIA Cutaneous Melanoma AJCC v8',
 'C137672': 'Pathologic Stage IIIB Cutaneous Melanoma AJCC v8',
 'C137673': 'Pathologic Stage IIIC Cutaneous Melanoma AJCC v8',
 'C137675': 'Pathologic Stage IIID Cutaneous Melanoma AJCC v8',
 'C137676': 'Stage IIID',
 'C137677': 'Pathologic Stage IV Cutaneous Melanoma AJCC v8',
 'C137951': 'Belzupacap Sarotalocan',
 'C138074': 'GPNMB Positive',
 'C138107': 'Autologous Genetically-modified MAGE-A4 C1032 T Cells',
 'C1387': 'MAGE-1 Antigen',
 'C139590': 'Vulvar Cancer TNM Finding v8',
 'C139618': 'Vulvar Cancer by AJCC v8 Stage',
 'C139632': 'Vaginal Cancer TNM Finding v8',
 'C139657': 'Vaginal Cancer by AJCC v8 Stage',
 'C140044': 'Penile Cancer TNM Finding v8',
 'C140075': 'Penile Cancer by AJCC v8 Stage',
 'C140089': 'CDKN2B-AS1 wt Allele',
 'C140428': 'Urethral Cancer TNM Finding v8',
 'C140457': 'Urethral Cancer by AJCC v8 Stage',
 'C140470': 'Eyelid Carcinoma TNM Finding v8',
 'C140513': 'Eyelid Carcinoma by AJCC v8 Stage',
 'C140527': 'Conjunctival Carcinoma TNM Finding v8',
 'C140556': 'Conjunctival Melanoma TNM Finding v8',
 'C140557': 'Conjunctival Melanoma Clinical TNM Finding v8',
 'C140558': 'Conjunctival Melanoma Clinical Distant Metastasis TNM Finding v8',
 'C140559': 'Conjunctival Melanoma cM0 TNM Finding v8',
 'C140560': 'Conjunctival Melanoma cM1 TNM Finding v8',
 'C140561': 'Conjunctival Melanoma Clinical Primary Tumor TNM Finding v8',
 'C140562': 'Conjunctival Melanoma cTX TNM Finding v8',
 'C140563': 'Conjunctival Melanoma cT0 TNM Finding v8',
 'C140564': 'Conjunctival Melanoma cT1 TNM Finding v8',
 'C140565': 'Conjunctival Melanoma cT1a TNM Finding v8',
 'C140566': 'Conjunctival Melanoma cT1b TNM Finding v8',
 'C140567': 'Conjunctival Melanoma cT1c TNM Finding v8',
 'C140568': 'Conjunctival Melanoma cT1d TNM Finding v8',
 'C140569': 'Conjunctival Melanoma cT2 TNM Finding v8',
 'C140570': 'Conjunctival Melanoma cT2a TNM Finding v8',
 'C140571': 'Conjunctival Melanoma cT2b TNM Finding v8',
 'C140572': 'Conjunctival Melanoma cT2c TNM Finding v8',
 'C140573': 'Conjunctival Melanoma cT2d TNM Finding v8',
 'C140574': 'Conjunctival Melanoma cT3 TNM Finding v8',
 'C140575': 'Conjunctival Melanoma cT3a TNM Finding v8',
 'C140576': 'Conjunctival Melanoma cT3b TNM Finding v8',
 'C140577': 'Conjunctival Melanoma cT3c TNM Finding v8',
 'C140578': 'Conjunctival Melanoma cT3d TNM Finding v8',
 'C140579': 'Conjunctival Melanoma cT4 TNM Finding v8',
 'C140580': 'Conjunctival Melanoma Pathologic TNM Finding v8',
 'C140581': 'Conjunctival Melanoma Pathologic Distant Metastasis TNM Finding '
            'v8',
 'C140582': 'Conjunctival Melanoma pM1 TNM Finding v8',
 'C140583': 'Conjunctival Melanoma Pathologic Primary Tumor TNM Finding v8',
 'C140584': 'Conjunctival Melanoma pTX TNM Finding v8',
 'C140585': 'Conjunctival Melanoma pT0 TNM Finding v8',
 'C140586': 'Conjunctival Melanoma pTis TNM Finding v8',
 'C140587': 'Conjunctival Melanoma pT1 TNM Finding v8',
 'C140588': 'Conjunctival Melanoma pT1a TNM Finding v8',
 'C140589': 'Conjunctival Melanoma pT1b TNM Finding v8',
 'C140590': 'Conjunctival Melanoma pT2 TNM Finding v8',
 'C140591': 'Conjunctival Melanoma pT2a TNM Finding v8',
 'C140592': 'Conjunctival Melanoma pT2b TNM Finding v8',
 'C140593': 'Conjunctival Melanoma pT3 TNM Finding v8',
 'C140594': 'Conjunctival Melanoma pT3a TNM Finding v8',
 'C140595': 'Conjunctival Melanoma pT3b TNM Finding v8',
 'C140596': 'Conjunctival Melanoma pT3c TNM Finding v8',
 'C140597': 'Conjunctival Melanoma pT3d TNM Finding v8',
 'C140598': 'Conjunctival Melanoma pT4 TNM Finding v8',
 'C140599': 'Conjunctival Melanoma Pathologic Regional Lymph Nodes TNM Finding '
            'v8',
 'C140600': 'Conjunctival Melanoma pNX TNM Finding v8',
 'C140601': 'Conjunctival Melanoma pN0 TNM Finding v8',
 'C140602': 'Conjunctival Melanoma pN1 TNM Finding v8',
 'C140603': 'Uveal Melanoma TNM Finding v8',
 'C140604': 'Uveal Melanoma Clinical TNM Finding v8',
 'C140605': 'Uveal Melanoma Clinical Distant Metastasis TNM Finding v8',
 'C140606': 'Uveal Melanoma cM0 TNM Finding v8',
 'C140607': 'Uveal Melanoma cM1 TNM Finding v8',
 'C140608': 'Uveal Melanoma cM1a TNM Finding v8',
 'C140609': 'Uveal Melanoma cM1b TNM Finding v8',
 'C140610': 'Uveal Melanoma cM1c TNM Finding v8',
 'C140611': 'Uveal Melanoma Pathologic TNM Finding v8',
 'C140612': 'Uveal Melanoma Pathologic Distant Metastasis TNM Finding v8',
 'C140613': 'Uveal Melanoma pM1 TNM Finding v8',
 'C140614': 'Uveal Melanoma pM1a TNM Finding v8',
 'C140615': 'Uveal Melanoma pM1b TNM Finding v8',
 'C140616': 'Uveal Melanoma pM1c TNM Finding v8',

In [10]:
ncit_df = pd.DataFrame(ncit_dict.items(), columns=['code', 'concept'])
ncit_df.to_csv(
    os.path.join(filter_save_dir, f'NCIt_concepts_{ncit_search_term}.csv'),
    index=False
)  #Save NCIt outputs for future references

### Obtain taxonomy code
This can be used later to filter cell lines by species

In [11]:
species_search_term = 'Homo sapiens'

In [12]:
tax_id = obtain_taxonomy_id(species_search_term)

Taxonomy ID for Homo sapiens: 9606

### Obtain cell lines related to a search term
Cellosaurus API methods & exploration: https://api.cellosaurus.org/api-methods#/

In [13]:
cell_line_search_term = 'melanoma'
search_term_type ='di', #Because melanoma is a disease

In [14]:
all_cell_lines_data = obtain_all_cell_lines(
    cell_line_search_term,
    search_term_type,
    tax_id
)

Concepts obtained: 0 to 92
Total cell line(s) retrieved for melanoma: 92

In [15]:
cell_line_df = cell_lines_df_clearing(all_cell_lines_data)
cell_line_df = cell_line_df[[
    'cell_line_id',
    'cell_line_name',
    'organ',
    'site_type',
    'disease',
    'age',
    'sex',
    'category',
    'species'
]]  # Reorder the columns

cell_line_df

CVCL_M212 lacks derived-from-site-list
CVCL_M212 lacks derived-from-site-list
CVCL_HF01 lacks derived-from-site-list
CVCL_HF01 lacks derived-from-site-list
CVCL_HF13 lacks derived-from-site-list
CVCL_HF13 lacks derived-from-site-list
CVCL_V020 lacks derived-from-site-list
CVCL_V020 lacks derived-from-site-list
CVCL_VP94 lacks derived-from-site-list
CVCL_VP94 lacks derived-from-site-list
CVCL_F250 lacks derived-from-site-list
CVCL_F250 lacks derived-from-site-list
CVCL_B7TC lacks derived-from-site-list
CVCL_B7TC lacks derived-from-site-list
CVCL_B7TD lacks derived-from-site-list
CVCL_B7TD lacks derived-from-site-list
CVCL_C668 lacks derived-from-site-list
CVCL_C668 lacks derived-from-site-list
CVCL_C672 lacks derived-from-site-list
CVCL_C672 lacks derived-from-site-list
CVCL_C680 lacks derived-from-site-list
CVCL_C680 lacks derived-from-site-list
CVCL_A648 lacks derived-from-site-list
CVCL_A648 lacks derived-from-site-list
CVCL_1068 lacks derived-from-site-list
CVCL_1068 lacks derived-from-site-list

,cell_line_id,cell_line_name,organ,site_type,disease,age,sex,category,species
0,CVCL_M212,FRM [Human melanoma],NaN,NaN,Amelanotic melanoma,Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
1,CVCL_HF04,"Me14464,14464",Lymph node,Metastatic,Melanoma,Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
2,CVCL_HF01,Me10258,NaN,NaN,Melanoma,Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
3,CVCL_HE99,"Me4686,4686",Lymph node,Metastatic,Melanoma,Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
4,CVCL_HF02,Me1274,Lymph node,Metastatic,Melanoma,Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
...,...,...,...,...,...,...,...,...,...
87,CVCL_C680,"INT-MEL-17,Me4405,ME4405,ME-4405,ME 4405",NaN,NaN,Melanoma,83Y,Female,Cancer cell line,Homo sapiens (Human)
88,CVCL_A648,"INT-MEL-12,Me10538,ME10538,ME 10538,Me 10538,M...",NaN,NaN,Melanoma,56Y,Female,Cancer cell line,Homo sapiens (Human)
89,CVCL_1068,ACN,NaN,NaN,Melanoma,Age unspecified,Sex unspecified,Cancer cell line,Homo sapiens (Human)
90,CVCL_0V14,"Mel501A,MEL501A,501A,501 A",Not specified,Metastatic,Melanoma,Age unspecified,Male,Cancer cell line,Homo sapiens (Human)
91,CVCL_1133,"COLO 741,COLO-741,Colo741,COLO741,Colorado 741",Pelvic wall,Metastatic,Melanoma,69Y,Female,Cancer cell line,Homo sapiens (Human)

In [16]:
cell_line_df.to_csv(f'input/filters/cell_lines_{cell_line_search_term}.csv', index=False)

### Filter melanoma cell lines

#### Melanoma brain metastasis cell lines

In [17]:
df_mbm = cell_line_df[
    cell_line_df['organ'].str.contains('brain', case=False, na=False) &
    cell_line_df['site_type'].str.contains('metastatic', case=False, na=False)
] # These are all the melanoma that metastasizes to the brain

df_mbm = df_mbm.reset_index(drop=True)
df_mbm

Empty DataFrame
Columns: [cell_line_id, cell_line_name, organ, site_type, disease, age, sex, category, species]
Index: []

In [18]:
df_mbm.to_csv(f'input/filters/cell_lines_mbm.csv', index=False)

#### Uveal melanoma cell lines

In [19]:
df_uveal = cell_line_df[
    cell_line_df['disease'].str.contains('uvea', case=False, na=False)
] #These are all the uveal melanoma, including the in situ and metastatic ones that can go to various locations (can be further specified)

df_uveal = df_uveal.reset_index(drop=True)
df_uveal

Empty DataFrame
Columns: [cell_line_id, cell_line_name, organ, site_type, disease, age, sex, category, species]
Index: []

In [20]:
df_mbm.to_csv(f'input/filters/cell_lines_um.csv', index=False)

## Obtain all astrocyte cell lines

### Obtain cell lines related to a search term

In [21]:
cell_line_search_term = 'astrocyte'
search_term_type = 'cell-type' #Because astrocyte is a cell type

In [22]:
all_cell_lines_data = obtain_all_cell_lines(
    cell_line_search_term,
    search_term_type,
    tax_id
)

Concepts obtained: 0 to 19
Total cell line(s) retrieved for astrocyte: 19

In [23]:
cell_line_df = cell_lines_df_clearing(all_cell_lines_data)
cell_line_df = cell_line_df[[
    'cell_line_id',
    'cell_line_name',
    'organ',
    'site_type',
    'disease',
    'age',
    'sex',
    'category',
    'species'
]]  # Reorder the columns

cell_line_df

CVCL_AQ52 lacks age
CVCL_AQ52 lacks sex
CVCL_AQ52 lacks derived-from-site-list
CVCL_AQ52 lacks derived-from-site-list
CVCL_AQ52 lacks disease-list
CVCL_4U69 lacks disease-list
CVCL_B4IH lacks disease-list
CVCL_X371 lacks disease-list
CVCL_E3G4 lacks disease-list
CVCL_E3G5 lacks disease-list
CVCL_Z595 lacks disease-list
CVCL_Z596 lacks disease-list
CVCL_5G14 lacks disease-list
CVCL_3797 lacks disease-list
CVCL_D5B6 lacks disease-list
CVCL_D5B7 lacks disease-list
CVCL_5G13 lacks disease-list
CVCL_C3HJ lacks disease-list
CVCL_VP19 lacks disease-list
CVCL_VP18 lacks disease-list
CVCL_5F78 lacks disease-list
CVCL_IM78 lacks disease-list
CVCL_B5WG lacks age
CVCL_B5WG lacks sex
CVCL_B5WG lacks disease-list

,cell_line_id,cell_line_name,organ,site_type,disease,age,sex,category,species
0,CVCL_AQ52,Astro.4U,NaN,NaN,NaN,NaN,NaN,Finite cell line,Homo sapiens (Human)
1,CVCL_4U69,"HASTR/ci35,Human ASTRocyte/conditionally immor...",Brain,In situ,NaN,4M,Sex unspecified,Conditionally immortalized cell line,Homo sapiens (Human)
2,CVCL_B4IH,A206,Fetal brain,In situ,NaN,12-16FW,Sex unspecified,Transformed cell line,Homo sapiens (Human)
3,CVCL_X371,A735,Fetal brain,In situ,NaN,12-16FW,Sex unspecified,Transformed cell line,Homo sapiens (Human)
4,CVCL_E3G4,NHA E6/E7/hTERT/Ras,Brain,In situ,NaN,Age unspecified,Sex unspecified,Transformed cell line,Homo sapiens (Human)
5,CVCL_E3G5,NHA E6/E7/hTERT/Ras/Akt,Brain,In situ,NaN,Age unspecified,Sex unspecified,Transformed cell line,Homo sapiens (Human)
6,CVCL_Z595,SK-astrocyte-IDH1,Brain,In situ,NaN,Age unspecified,Sex unspecified,Telomerase immortalized cell line,Homo sapiens (Human)
7,CVCL_Z596,SK-astrocyte-IDH1-R132H,Brain,In situ,NaN,Age unspecified,Sex unspecified,Telomerase immortalized cell line,Homo sapiens (Human)
8,CVCL_5G14,"SVG,SV40 immortalized Glial cell",Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
9,CVCL_3797,"SVG p12,SVGp12,SVG(P12)",Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
10,CVCL_D5B6,"SVG-10B1,10B1",Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
11,CVCL_D5B7,"SVG-5F4,5F4",Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
12,CVCL_5G13,SVG-A,Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
13,CVCL_C3HJ,SVG-A CHMP1A null,Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
14,CVCL_VP19,SVG-A Msh3 1.7X,Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
15,CVCL_VP18,"SVG-A Msh3-/-,Msh3-/- SVG-A",Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
16,CVCL_5F78,SVG-TH,Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
17,CVCL_IM78,SVGR2,Fetal brain,In situ,NaN,8-12FW,Male,Transformed cell line,Homo sapiens (Human)
18,CVCL_B5WG,"IM-HA,IMmortalized-Human Astrocytes","Brain, cerebral cortex",In situ,NaN,NaN,NaN,Transformed cell line,Homo sapiens (Human)

In [24]:
cell_line_df.to_csv(f'input/filters/cell_lines_{cell_line_search_term}.csv', index=False)